### ISSUE TITLE
Water as coolant?

### ISSUE THREAD

**Issue by MrAmericanMike** [ZeroNoRyouki/BigReactors#1]
Well, clearly water wasn't a good idea from me to use. But when trying it, it crashes the world.

http://imgur.com/a/MIgtp

That's how the game freezed and the error on console is http://pastebin.com/9NpATGaf

Using ExtremeReactors-1.9.4-0.4.5.6.jar
Forge 12.18.1.2068
Minecraft 1.10.2

**Comment by ZeroNoRyouki** [comment]
Thank you for the report

Fixed

**Comment by MrAmericanMike** [comment]
Thanks. It even loads again the corrupted world :D Gonna keep doing some tests, as why my reactor isn't producing any power, not sure what I would be missing, long time since I used the mod back in 1.7.10 :D

**Comment by ZeroNoRyouki** [comment]
;)

What is your reactor configuration?

**Comment by MrAmericanMike** [comment]
Got it working. Just made a 7x7x7 for testing with some Diamonds Blocks inside.

I messed up that I didnt had an "Access Port" as output for the ingots to go, so it wasn't working. I placed the coolant port, got confused by the similar textures.

**Comment by ZeroNoRyouki** [comment]
I'm glad it's working now :)
