### ISSUE TITLE
Config for using steel instead of iron not working

### ISSUE THREAD

**Issue by MCEventHorizon** [ZeroNoRyouki/BigReactors#10]
I have a few mods that add steel ingot like Mekanism, TechReborn, IC2 etc. but the recipe uses Iron still.

**Comment by psychofad** [comment]
I have also noticed this.

**Comment by ZeroNoRyouki** [comment]
Uhm it looks like we forget to remove that from the config file. That option is ignored, the new blocks tiers we will introduce will use stell natively
