### ISSUE TITLE
[1.11.2] Cannot view computer port recipe.

### ISSUE THREAD

**Issue by savosdarkran** [ZeroNoRyouki/BigReactors#100]
Hello,

I have open computers and extreme reactors installed on a 1.11.2 pack but I cannot view the computer port recipe.

Extreme Reactors: 0.4.5.28
Open Computers: 1.7.0.6

Any advice?

Appreciate your help.

**Comment by ZeroNoRyouki** [comment]
Their modid changed in 1.11 so I need to patch things on my side. I'll push out a new version asap

**Comment by savosdarkran** [comment]
Awesome!  Thank you so much!

**Comment by ZeroNoRyouki** [comment]
Just a quick update: support is ready on my side. I'am waiting for them to fix a bug in OC that's preventing it to load

**Comment by savosdarkran** [comment]
Amazing!  Thank you!

**Comment by ZeroNoRyouki** [comment]
I've just pushed out 0.4.5.29 and the OC support code. When they fix things on their side you should be good to go :)

**Comment by savosdarkran** [comment]
Are you referring to the Transformer issue on their tracker?  If so, I've subscribed to it so I shouldn't be bothering you anymore :D  Appreciate your help!

**Comment by ZeroNoRyouki** [comment]
Yup, that's the one. Don't worry, and have fun with the mod :)
