### ISSUE TITLE
[1.10] Breaks ThermalFoundation Steam texture

### ISSUE THREAD

**Issue by HanFox** [ZeroNoRyouki/BigReactors#101]
For some reason this breaks the TF steam texture?

I can't see anything in the log about it.

ExtremeReactors-1.10.2-0.4.5.28.jar

**Comment by ZeroNoRyouki** [comment]
I just tested this with ER 1.10.2-0.4.5.28 and TE 1.10.2-5.0.4.90 / TF 1.10.2-2.0.5.81 and it's working fine:

![2017-04-30_15 32 59](https://cloud.githubusercontent.com/assets/7107662/25564770/8461ae04-2dba-11e7-8986-62f70b991ae9.png)

**Comment by HanFox** [comment]
Mods:
  CodeChickenCore-1.10.2-2.4.1.102-universal
  CodeChickenLib-1.10.2-2.5.7.241-universal
  CoFHCore-1.10.2-4.1.1.156-universal
  ExtremeReactors-1.10.2-0.4.5.28
  Hwyla-1.8.11-B25_1.10.2
  jei_1.10.2-3.14.7.416
  NotEnoughItems-1.10.2-2.1.3.206-universal
  RedstoneArsenal-1.10.2-2.0.3.29-universal
  SimplyJetpacks2-1.10.2-2.1.0.39
  ThermalExpansion-1.10.2-5.0.4.90-universal
  ThermalFoundation-1.10.2-2.0.5.81-universal
  zerocore-1.10.2-0.1.0.5
  
  
![2017-04-30_14 58 17](https://cloud.githubusercontent.com/assets/1781312/25564921/88ac4c6c-2db5-11e7-8416-d1da0443dc2e.png)

Removing ExtremeReactors the textures load correctly.

In fact, with ER enabled I can't even put steam in a ThermalExpansion Steam Dynamo.

**Comment by ZeroNoRyouki** [comment]
That's TF Steam (and so it's texture). I use the currently registered steam fluid or add my own, I don't modify the existing one.

I tested this again with exact mods/versions you posted and it's working fine. Which version of Forge are you using?

You can't add a bucket of steam to the Dynamo by just clicking it with it even without ER

**Comment by HanFox** [comment]
I was using Forge 2281.

So I tried 2185 and made a new world and everything's working correctly.

My old world is still having issues though. I guess something's messed up somewhere with that now (gladly it was just for texture testing).

Anyway, sorry, I guess Forge has shit the bed recently.

**Comment by ZeroNoRyouki** [comment]
No problem
