### ISSUE TITLE
Best Coolant for Extreme Reactors ?

### ISSUE THREAD

**Issue by llloyd4** [ZeroNoRyouki/BigReactors#102]
Let's see, this is Extreme Reactors version 0.4.5.28 for 1.10.2 (ExtremeReactors-1.10.2-0.4.5.28.jar) Been trying a lot of expensive things for my 11 x 11 x 11 reactor and so far, nothing, everything I've tried the core and casing have remained at max heat. I've tried liquid ender (pre Thermal Expansion), blocks of viberant alloy, cryothium (post Thermal Expansion), etc, etc, etc and nada, What is the best coolant for my reactor? >.< Heck, 1.7.10 and earlier Big Reactors have all used Cyrothium as it was the best coolant. Now, nope, 2360C on casing and core. >.< Same with Viberant blocks, same with liquid ender.

**Comment by lordcheeto** [comment]
Fuel rod configuration?

**Comment by RogueLogic** [comment]
There is no specific"best" fuel. They are different, find what works best in your reactor.

**Comment by llloyd4** [comment]
@Lordcheeto Standard staggered design so there is empty space around every rod to put coolant.

**Comment by lordcheeto** [comment]
This is out of date, since it's based on Big Reactors, not Extreme Reactors, but you mean [this config](http://br.sidoh.org/#reactor-design?length=11&width=11&height=11&activelyCooled=false&controlRodInsertion=0&layout=12CXCXCXCXCX3CXCXCXCX3CXCXCXCXCX3CXCXCXCX3CXCXCXCXCX3CXCXCXCX3CXCXCXCXCX3CXCXCXCX3CXCXCXCXCX12C)?

**Comment by lordcheeto** [comment]
I don't think (highly doubt) there's any configuration for an 11x11x11 reactor that can run at 0% control rod insertion and not run hot. Try messing with the control rod insertion.

**Comment by llloyd4** [comment]
Like this

http://br.sidoh.org/#reactor-design?length=9&width=9&height=9&activelyCooled=false&controlRodInsertion=0&layout=10CXCXCXCX3CXCXCX3CXCXCXCX3CXCXCX3CXCXCXCX3CXCXCX3CXCXCXCX10C

Oh ? But that would drop the RF/t out if I insert the rods? I am trying to balance efficiency with RF/t out. Got a *lot* ways until the Tier 7 Draconic sphere is full. O.o

**Comment by lordcheeto** [comment]
Ok, 9x9x9 internal. That would drop the reaction rate, and thus RF/t, but increase efficiency. Another option would be to remove fuel rods (generating less heat), and spread them around with more coolant in between. That would also generate less RF/t, but be more efficient at low control rod insertions. What is your goal RF/t?

**Comment by llloyd4** [comment]
As much as possible? I am only up to 300 B RF out of 2.14 T RF.

**Comment by ZeroNoRyouki** [comment]
Guys please move this discussion to the [forum](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2731713-extreme-reactors-a-big-reactors-port-to-mc-1-9-4-1). The issue tracker is not the right place for it. Thank you
