### ISSUE TITLE
GitHub not updated since October 2016.

### ISSUE THREAD

**Issue by lordcheeto** [ZeroNoRyouki/BigReactors#103]
Beta versions of the mod for MC 1.11.2 [have been released](https://mods.curse.com/mc-mods/minecraft/250277-extreme-reactors) on Curse, but this GitHub repo has not been updated since October 2016. Can we get the source for the most recent version?

**Comment by RogueLogic** [comment]
#64

**Comment by lordcheeto** [comment]
Ah, I looked through closed issues, but only the last 20 or so.
