### ISSUE TITLE
fluid.cyanite is unnamed

### ISSUE THREAD

**Issue by TheCodedOne** [ZeroNoRyouki/BigReactors#107]
fluid.cyanite has no lang name but yellorium does

![image](https://cloud.githubusercontent.com/assets/17037059/26490503/7503311e-4203-11e7-9968-b8fe5a5021db.png)
![image](https://cloud.githubusercontent.com/assets/17037059/26490516/840f0728-4203-11e7-91ea-7c4a7aaaff58.png)

**Comment by ZeroNoRyouki** [comment]
Fixed in the next release
