### ISSUE TITLE
[1.10.2][Question / Possible Issue] Thermal Foundation (Gelid Cryotheum) is not supported?

### ISSUE THREAD

**Issue by BrisingrAerowing** [ZeroNoRyouki/BigReactors#108]
I was looking at a tutorial for the original Big Reactors mod (most things still apply, it seems), and the guy was using Gelid Cryotheum from Thermal Foundation as a coolant (in a passive reactor).

I have an active reactor and, since I play in creative, an infinite supply of Gelid Cryotheum using a creative fluid supplier from another mod. No matter what type of pipe I connect to the reactor coolant port (in input mode), Gelid Cryotheum isn't put into the reactor.

It is not supported, or am I missing something obvious (or not so obvious)?

I am going to use water in the meantime, as I know that works:

ER: 0.4.5.29
Forge: 12.18.3.2297

**Comment by ZeroNoRyouki** [comment]
Gelid Cryotheum is not a coolant, is a reactant (like anything else you place inside the reactor). You need place those blocks inside the reactor manually (or with a "block placer" / "fluid placer" block from another mod

Coolant Ports are used to exchange water and steam between a Turbine (or other manchine) and an actively cooled reator
