### ISSUE TITLE
[Feature Request] Integration with the Pressure Pipes mod

### ISSUE THREAD

**Issue by BrisingrAerowing** [ZeroNoRyouki/BigReactors#109]
[Pressure Pipes](https://minecraft.curseforge.com/projects/pressure-pipes) is a mod I use for fluid storage / transport, as it supports (theoretically) infinite throughput of fluids, even supporting multiple fluids on one pipe.

Having direct support for this mod would help with transferring massive amounts of steam from an active reactor to a turbine, and supplying lots of coolant to a reactor.

I can work around this by using a couple of other blocks from the mod, but direct support would be awesome.

**Comment by ZeroNoRyouki** [comment]
What kind of direct support? If he still use the forge capability system for fluid transfer it's already "supported" (like any other mod that do so). I've used pressure pipes in the past to test the coolant ports and it worked fine

**Comment by BrisingrAerowing** [comment]
I hadn't tested it yet. I'll take a look once I get MC running again (I keep getting a startup crash even though I haven't changed anything...)
