### ISSUE TITLE
Redstone port buggy

### ISSUE THREAD

**Issue by psychofad** [ZeroNoRyouki/BigReactors#11]
When I set the redstone port to output a redstone signal when the power gets to a certain level, it attempts to do so, but the redstone attached to it is not updated unless I do a block update next to it.  I have tried this with vanilla redstone as well as EnderIO Insulated Redstone Conduits and the block will change the red square texture to a brighter color, but it will not output a signal unless I place and break a block next to it.  This is also true for when it shuts off, the redstone will remain active unless a block update occurs.  

The redstone port seems work correctly with all of the input options I have tested.

forge-1.10.2-12.18.1.2076
ExtremeReactors-1.9.4-0.4.5.10

**Comment by ZeroNoRyouki** [comment]
Thank you for the report. The fix will be included in the next release of the mod
