### ISSUE TITLE
Conflict with Railcraft

### ISSUE THREAD

**Issue by Sekra** [ZeroNoRyouki/BigReactors#110]
I'm having an issue with Extreme Reactors conflicting with a Railcraft recipe;

Currently for Railcraft Creosote oil is created by cooking coal or charcoal in a normal furnace, unfortunately with Extreme Reactors this gets overridden as Graphite Bars..
Although this is more likely an issue with Railcraft as the method of creating Creosote Oil is a temporary revert to old functionality, I still wanted to let you guys know about this too.

**Comment by ZeroNoRyouki** [comment]
You can disable our smelting recipes and enable the crafting ones (gravel + coal / charcoal) in the config file

**Comment by Sekra** [comment]
This is good to know. Railcraft guys also informed me that this issue will be resolved in their coming update as more functionality is restored for the mod and the temporary reversion to old functionality is rolled back as they keep re-building the features of the mod. They also said they have alt recipes in their mod we can enable. And to be more precise about the versions, this is an issue with Railcraft 10.x versions, but will be fixed in Railcraft 10.3 according to their replies.
