### ISSUE TITLE
[1.10.2] Question Particales

### ISSUE THREAD

**Issue by YOYOK9** [ZeroNoRyouki/BigReactors#112]
So just a question about the reactor particles. Is there by any chance a way to turn off the reactor and turbine particles on a server? I have players on mine making huge reactors (or small ones) and just getting destroyed by the massive amount of particle lag.

**Comment by ZeroNoRyouki** [comment]
Hi there,
I spawn particles client-side so I'm not sure where that lag is coming from

**Comment by YOYOK9** [comment]
weird. is there a way to try to disable them for testing purposes?

**Comment by ZeroNoRyouki** [comment]
Not at the moment (except for the particles setting in the option menu of Minecraft itself). I'll add a config option in the next release.

Keep in mind that the Fuel Rod code that spawn the particles  it's not even loaded if the mod run on a server

**Comment by ZeroNoRyouki** [comment]
Hi,
0.4.5.30 is out with the new config options

**Comment by ZeroNoRyouki** [comment]
Hi, did you check the problem with the new version?

thank you
Z

**Comment by ZeroNoRyouki** [comment]
Closing...
