### ISSUE TITLE
[Suggestion] Add "poison" effect when handling uranium

### ISSUE THREAD

**Issue by Tomson124** [ZeroNoRyouki/BigReactors#113]
BigReactors and Extreme Reactors always try to achieve a mix of realism and game balance, but äI think the addition of a Radiation poison effect and Hazmant suit armor would be cool. I started with that in my initial rewrite of the mod, I could do the feautre and just make a pull request :)
Some kind of radiation output from the reacor which has to be shielded with special blocks would be a cool feature, too for the future. I am glad when I can help updating/maintaining the mod.

P.S. Maybe change textures to the ones from Unity? The current ones look so "out of place" in a minecraft world.

**Comment by ZeroNoRyouki** [comment]
We are already working on something like that, and making new textures for the new blocks ;)

**Comment by Tomson124** [comment]
Okay, just tell me when and if I can help ;) Just hit me up on discord
