### ISSUE TITLE
[1.12] Creative Tab Leak

### ISSUE THREAD

**Issue by TheCodedOne** [ZeroNoRyouki/BigReactors#114]
as can be seen in the image, some ER stuff is showing in creative tabs that aren't its own, i made a reddit post last week on how to fix this https://redd.it/6h9z7f
![image](https://user-images.githubusercontent.com/17037059/27434057-3719d6b2-574f-11e7-9be2-852860717f06.png)

**Comment by ZeroNoRyouki** [comment]
This is ridiculous...

**Comment by ZeroNoRyouki** [comment]
"Fixed" in the next release
