### ISSUE TITLE
1.10.2 Fuel Eject only giving 1/9th of the fuel

### ISSUE THREAD

**Issue by OriginalMaRul** [ZeroNoRyouki/BigReactors#116]
Don't know if this has been fixed. In FTB Beyond 1.9.0 since I worry about losing fuel when upgrading a reactor. I found that my current build could hold 2 stacks of blocks, but would only eject 2 stacks of ingots before it was empty. I can't tell if this is a conflict bug or a conversion mix up in the mod.

**Comment by ZeroNoRyouki** [comment]
I cant' reproduce this. Do you have the same problem with the standard config?
I just fixed a bug the produced MORE fuel and will give MORE ingots than the one you put in in the first place so this is kind of strange..

**Comment by luigge** [comment]
I'm playing on minecraft 1.10.2 and noticed that if you shift click to eject fuel, only ejects one stack and the rest disappear

**Comment by ZeroNoRyouki** [comment]
@luigge could you please give me the steps to reproduce this? What is your reactor configuration? How much fuel did you have in it before removing it?

**Comment by luigge** [comment]
my reactor is a (if I'm not wrong) 21x21x20   20 is the hight. if I put a lot of yellorium blocks and then try to remove the fuel with shift click to remove all, the reactor only gives me a stack of yellorium ingots

minecraft 1.10.2
mod version 0.4.5.45 lastest one

**Comment by ZeroNoRyouki** [comment]
@luigge: Sorry, I misread your original question. If you are holding shift while clicking on the eject button you will get the amount of fuel (or waste) that will fit in the access port slot (like always) but the remaining fuel (or waste) inside the reactor will be deleted as well (this is a way to quickly empty the reactor)
