### ISSUE TITLE
0.4.5.10 - Possible Turbine Fluid Port/Mekanism Interaction Bug

### ISSUE THREAD

**Issue by RocketPhoenix** [ZeroNoRyouki/BigReactors#12]
[Reactors version 1.9.4-0.4.5.10]
[modpack - All the Mods v1.19]
[forge v12.18.1.2076]
On a multiplayer server, I was fiddling with the turbine fluid ports (possibly connected to a Mekanism pipe filled with water) and at some point broke the turbine multiblock (possibly one of the fluid port blocks)
This resulted in the server crashing, and now the server crashes whenever I log in (rendering the chunks with the turbine)
I attempted to recreate this in single player and was unable
There were two fluid ports in a reactor and two in a turbine (two meters apart). I pumped water into one reactor port and accidentally pumped water out the other reactor port (is that an intended feature?). I broke and replaced the Mek pipes many times to remove the water from them, and also toggled the input/outputs on all fluid ports many times. The Mek pipes were top-tier.
I'm not exactly sure what the problem was or if it's even a bug on your side, but I'm posting this here just in case.

I believe these are my crash reports:
http://pastebin.com/zy7kVFVG
http://pastebin.com/k3x8qMVa

Thank you for your time

[crash-2016-09-05_21.58.53-client.txt](https://github.com/ZeroNoRyouki/BigReactors/files/457987/crash-2016-09-05_21.58.53-client.txt)
[crash-2016-09-06_00.17.08-client.txt](https://github.com/ZeroNoRyouki/BigReactors/files/457988/crash-2016-09-06_00.17.08-client.txt)

**Comment by ZeroNoRyouki** [comment]
Looking at the report, the crash is nowhere near ER code (one is in the video setting GUI of MC). Are you sure you posted the correct crash reports?

Also, please update to the last version of Extreme Reactors and Mekanisms

**Comment by RocketPhoenix** [comment]
I'm reaching out to the server owner to receive the server-side crash reports from a time range in which the server crashed. My client only crashed during the first event, but I believe the server crashed every time and I'm sure of certain times it happened. I will make a post when I receive feedback.
As far as updating the mods goes, I don't believe the server admin and all players on the server would wish to manually make editions to the public mod pack we are playing on. I am sorry for any inconveniences this causes.
Thank you for your time

**Comment by ZeroNoRyouki** [comment]
Don't worry.

I'll wait for the new logs then

**Comment by RocketPhoenix** [comment]
If the server time zone is near mine, then this should definitely be one of the reports:
http://pastebin.com/u0dBs23U
If the problem isn't related to this mod, feel free to close the issue. I don't think anyone else has encountered this bug, so it may not be very high-priority.
Though I would like to know what mod (if any) caused this so it might be resolved.
And thank you again, I really appreciate your patience.

**Comment by ZeroNoRyouki** [comment]
Yup, that's a bug of mine

The fix will be included in the next release of the mod (a couple of days I think)
