### ISSUE TITLE
[1.12] IC2 & ImmersiveEngineering Uranium Blocks cant be used as fuel

### ISSUE THREAD

**Issue by Morpheus1101** [ZeroNoRyouki/BigReactors#121]
compatibility {
    # If true, automatically adds all unregistered uranium ingots found as clonesof standard yellorium fuel
    B:autoAddUranium=true

Unless im mis understanding, ic3 Uranium block "should" be able to be used as fuel as presently instead of getting an Yellorite block you get an IC2 block in the pack ATC

Forge *.2415
ER 0.4.5.33

**Comment by ZeroNoRyouki** [comment]
If that option is true, "ingotUranium" is added as a source of yellorium fuel. So any ingot that is registered in the ore dictionary as "ingotUranium" will behave as the standard yellorium ingots (adding an IE uranium ingot in the reactor will do the same thing as adding a yellorium ingot)
