### ISSUE TITLE
[1.12] Crash when using a reactor

### ISSUE THREAD

**Issue by Furuchiru** [ZeroNoRyouki/BigReactors#123]
I'm getting a crash while trying to use a reactor, I was using it fine a few minutes ago... Idk what happaned.
I saw something about "digital miner" in the crash report, so I'll post this in Mekanism web too.
PS: Sorry if my english it's bad...

Crash report: https://pastebin.com/9UBwrSAM
Log: https://drive.google.com/file/d/0B5jlv6laZq5UUzNic3o2OGNoZlU/view?usp=sharing

**Comment by ZeroNoRyouki** [comment]
Uhm this really don't look like a crash related to Extreme Reactors

**Comment by Furuchiru** [comment]
Oh...ok, I'm still waiting for Mekanism's answer...
But it's possible to have a crash not related with a mod, when it's a machine of that mod that triggers it?

**Comment by Furuchiru** [comment]
Well, Mekanism poeple told me to try to remove the digital miner then tried using the reactor and it worked fine, so it's some kind of strange bug I think. Lol, i'm closing this. Thanks

**Comment by ZeroNoRyouki** [comment]
No problems
Z
