### ISSUE TITLE
EnderIO Turbine Steam!?!??

### ISSUE THREAD

**Issue by FrozenSpartan** [ZeroNoRyouki/BigReactors#124]
I have been looking at every youtube tutorial out there and I still cannot understand why steam is not being pumped into my turbine. Have I constructed something incorrectly?

Turbine: https://gyazo.com/baa4034652fa403f3ce5e6de5ce7732a

Reactor (Full of Steam): https://gyazo.com/ac24f5f96f0f300f2b66f9833d1db875

Turbine Controller (No Steam): https://gyazo.com/1b517946e8c542fc73302c49048fc9e6

Ender Fluid Conduits and Coolant Ports: https://gyazo.com/5b9703268af64bb091535d9558b121b5

Automated Yellorium and Water Pumping Into Reactor (Don't Think This Is The Problem): https://gyazo.com/f5962f9bf1b06ad7dcdb4df7c97c27f7

PLEASE HELP!!!!!!!!! <3

EDIT: I have found out that my red to red pipe is pumping out water, but I don't know how to fix this!

EDIT 2: IVE GOT IT TO PUMP STEAM! I just switched the coolant ports around and it worked somehow, though I don't know how to pump out more steam. The max tick I'm getting is 200/t

**Comment by ZeroNoRyouki** [comment]
The coolant ports transfer rate is only capped by the amount of fluid the reactor (or turbine) hold in it's internal buffer. That 200 mb/t come from the pipes you are using
