### ISSUE TITLE
Computer Port Issues

### ISSUE THREAD

**Issue by WebSkyNetCloud** [ZeroNoRyouki/BigReactors#125]
The computer port in this mod doesn't seem to support the mod Computality and what it does. As Computality is a spin off of ComputerCraft but dose seem to be the same as it was change and mod support was taken out so this mod would need to get the support for that mod again so that the issues i wanted to know if that could be fixed.

**Comment by ZeroNoRyouki** [comment]
It look like that they changed the modid of the mod, so it's not recognized anymore. Not sure why they did that. I'll add this to my todo list

**Comment by WebSkyNetCloud** [comment]
Thx you so much <3

**Comment by ZeroNoRyouki** [comment]
There is a 1.12 version of Computer Craft being worked on. I'll wait a bit and see how that turn out

**Comment by necrologics** [comment]
might as well add this in as well, open computers 1.12.1 will also need support as well,

**Comment by ZeroNoRyouki** [comment]
ComputerCraft for 1.12 is out

I'm rewriting the OpenComputers side of things to use their capabilities system

**Comment by ZeroNoRyouki** [comment]
OpenComputers support is back on all supported MC versions
