### ISSUE TITLE
Ejecting blutonium gives back yellorium

### ISSUE THREAD

**Issue by josephcsible** [ZeroNoRyouki/BigReactors#126]
If you put blutonium ingots in a reactor and then eject them with the "Eject fuel" button, you get yellorium ingots back. Version 1.12-0.4.5.34.

**Comment by ZeroNoRyouki** [comment]
Blutonium is, at the moment, just an alias for Yellorium when fuel is concerned. As the fuel in the Reactor is Yellorium, you get back Yellorium ingots.
