### ISSUE TITLE
Dupe

### ISSUE THREAD

**Issue by matrix2021** [ZeroNoRyouki/BigReactors#127]
When you put yellorium blocks to reactor and press "Eject Fuel" you got larger amount of ingots than those that are included in craft of these blocks. I tried it on 5x5x5 reactor.
Video: https://www.youtube.com/watch?v=ZOnBTf003BA

**Comment by ZeroNoRyouki** [comment]
You found a very old bug my friend that had nothing to do with removing fuel from the reactor ... 

Fixed in the next release
