### ISSUE TITLE
cant find yellorium ingot in creative list

### ISSUE THREAD

**Issue by LocoMinerDad** [ZeroNoRyouki/BigReactors#128]
Hi there,

Playing minecraft 1.12 forge .12443 mod v5.34
I can't find the reactors tab and when I type yellorium ingot nothing comes up. I am trying to test a reactor design.

Please help

thank you

**Comment by ZeroNoRyouki** [comment]
Sorry for the late replay but I can't really reproduce this..

![tab](https://user-images.githubusercontent.com/7107662/30655744-2ad00ed8-9e32-11e7-92fe-83fd9379e4d8.png)
