### ISSUE TITLE
Add Computality Support ? (Computality change from CC)

### ISSUE THREAD

**Issue by DrumSlayers** [ZeroNoRyouki/BigReactors#130]
Hello,
I'm a long date user of Big reactor, 
And before Extreme Reactor i've used computers from computercraft to control reactor & turbines,

**## BUT** 

Now Computercraft is Computality , and the API appear to change from Computercraft,
As mentionned by Dr_Codex, maintener of Computality, 

> in 1.12, i changed a bunch of things, mods adding support for computercraft DO NOT work with computality, they need direct computality support...
[(https://minecraft.curseforge.com/projects/computality?comment=37)]

## **So , my request is , can you update the API in Extreme Reactor to fit with Computality?**
Hope the Rednet & Computer port work again (i think you know the issue because the Computer port is uncraftable)

**There is a HUGE amount of lua scripts created for Big Reactor,  and the community is missing this now...**
(And of course, EnderIO is not updated so no monitoring)

For informations, i'm using Minecraft 1.12.1 with Forge 14.22.0.2467,
Mods Computality 1.82.3
Extreme Reactor 1.12-0.4.5.34

Thank you a lot :)
Hope you're still active on the project! 😄

**Comment by ZeroNoRyouki** [comment]
Please check #125
