### ISSUE TITLE
[1.12.1] OpenComputers Problem

### ISSUE THREAD

**Issue by UnPure** [ZeroNoRyouki/BigReactors#132]
Hey there.
I'm currently trying to setup my opencomputer to monitor my reactor.
The script that i used in the past seems not to work anymore.
Are there any changes about that? Or isnt that integrated currently?

**Extreme Reactors:** 0.4.5.34
**OpenComputers:** 1.7.0.4
**Forge:** 14.22.1.2481

**Comment by ZeroNoRyouki** [comment]
There is currently a bug in OC that's preventing the computer ports to be recognized. I've rewritten the code on my side to go around that and I'm currently testing it (it should be ok for 1.12 and 1.12.1)

So far so good ...

![oc](https://user-images.githubusercontent.com/7107662/30553780-9148c54c-9ca2-11e7-88a6-b5a57c892b97.png)

Also, please see #125

**Comment by UnPure** [comment]
How is https://github.com/ZeroNoRyouki/BigReactors/issues/125 related to this?
