### ISSUE TITLE
[1.12.1] Reactor forming too late? (OpenComputers)

### ISSUE THREAD

**Issue by UnPure** [ZeroNoRyouki/BigReactors#134]
Hey there.
My problem could be related to your rewrite (https://github.com/ZeroNoRyouki/BigReactors/issues/125) of the OpenComputers integration.
I'm running a script to monitor the reactor with OpenComputers.
The programm is working fine if i start it by hand but its not if the client/server restarts.
I feel like the reactor isnt forming fast enough or anything else isnt working as it should.

This is running when the computer starts:
https://pastebin.com/sjJi0bum

It was working fine with Extreme Reactors on 1.10.2 so its not about the lua script.

When the server starts, the script is crashing, if i run the script by hand, its working.
I tried sleep commands any many other things but it doesnt matter what i do, after a restart its crashing the first time the script runs.

Forege: 14.22.0.2485
Extreme Reactors: 0.4.5.40
OpenComputers: 1.7.0.4

**Comment by UnPure** [comment]
While looking at something else i saw this log entry on startup:

`[Server thread/WARN] [opencomputers]: A component of type 'br_reactor' disappeared (742a7b34-0ac4-4bf6-9730-c07591581a23)! This usually means that it didn't save its node.`

**Comment by Ava2201** [comment]
This happens after a Server restart(script above is on autostart)

https://imgur.com/a/NIISY

**Comment by ZeroNoRyouki** [comment]
Actually, it was the other way around. The reactor state change before the actual tick and the computer port was not saving/reloading the node state correctly

Keep in mind that I was forced to switch to using OC cababilities and the computer port join/leave the OC network when it is attached/detached from it's controller. In my test this is not causing problems but there could be some corner cases where a change to existing script could be needed

The fix will be included in the next release (1.10.2, 1.11.2, 1.12.*)
