### ISSUE TITLE
1.10.2 Client crash in 0.4.5.42

### ISSUE THREAD

**Issue by silent-mobious** [ZeroNoRyouki/BigReactors#136]
I updated to ExtremeReactors-1.10.2-0.4.5.42 on my client and server.  Server was fine, however client crashes out immediately.  Failing back to .41 works.

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Extreme Reactors (bigreactors)
Caused by: java.lang.NoClassDefFoundError: erogenousbeef/bigreactors/common/multiblock/block/BlockReactorRedNetPort

Full crash log: https://pastebin.com/xKyMLRy2

Thanks a lot!

**Comment by BrisingrAerowing** [comment]
ER is using a development version of MFR, which has changes to the RedNet node system (from x/y/z coordinates to BlockPos). The current alpha release for 1.10.2 doesn't have those changes.

**Comment by ZeroNoRyouki** [comment]
I'm not using a development version of MFR, I'm using the last beta available on Curse (MineFactoryReloaded-[1.10.2]2.9.0B1-226) and both of the betas on Curse uses BlockPos for IRedNetInputNode / IRedNetOutputNode (and so does the last alpha release)

**Comment by ZeroNoRyouki** [comment]
Fixed in 0.4.5.43
