### ISSUE TITLE
gui seems glitched

### ISSUE THREAD

**Issue by pyscho974** [ZeroNoRyouki/BigReactors#138]
running space astronomy 2(ver. 1.3.2) ER ver.1.10.2-0.4.5.41. .

 we tried to tweak a turbine config to allow for 24 blocks in length(x,z).   that part works.. but the gui does not show any RPM speed either in numbers or color graph.
reassembled at 16 length and gui works fine.

**Comment by ZeroNoRyouki** [comment]
It's working fine for me (with the last version):

![2017-10-08_11 36 44](https://user-images.githubusercontent.com/7107662/31315684-8c591ad4-ac1d-11e7-8d5f-bfbf225ad775.png)
![2017-10-08_11 39 06](https://user-images.githubusercontent.com/7107662/31315685-8c596e62-ac1d-11e7-8267-be2f3245da6e.png)

Are you providing it enough steam? Do you see the turbine rotor spin while the gui is not showing any RPM ?

**Comment by pyscho974** [comment]
no.. no indication its running except for full steam and rf output.  you on 0.4.5.42?  pack has not updated to that version yet.. 
![2017-10-07_22 57 19](https://user-images.githubusercontent.com/31806577/31315750-3bb1a166-abe4-11e7-8d8a-d1094aa99b4e.png)

**Comment by ZeroNoRyouki** [comment]
The last version is 0.4.5.44 but nothing changed in the Turbine code between .41 and that, only computer-related stuff.

How many rotor blades do you have in there ?

**Comment by pyscho974** [comment]
hmm makes me wonder if its a mod conflict then in space astronomy 2..  had built 3 the turbines at 24.  80 blades.  7x7x24 and 7coils of electrum plus 1 space between coil and blades.  was just told when looked at this morning. the multiblock had not formed but was still taking steam and outputting power.

**Comment by ZeroNoRyouki** [comment]
Hi, do you have any update on this?

**Comment by pyscho974** [comment]
not at moment..  they ended  up just going back to the 16  block limit. is to be an update on mod pack today and ill retest it. sorry for long delay on reply

**Comment by MJRLegends** [comment]
Hey @ZeroNoRyouki im the Space Astronomy 2 pack owner. 

@pyscho974 you could of told me about this bug haha

**Comment by ZeroNoRyouki** [comment]
@MJRLegends hi there

@pyscho974 no problems. Let me know how the test goes ;)

**Comment by ZeroNoRyouki** [comment]
Closing...
