### ISSUE TITLE
Nether Ore in end

### ISSUE THREAD

**Issue by gigabit101** [ZeroNoRyouki/BigReactors#14]
fail ;)
![ss 2016-09-13 at 03 48 23](https://cloud.githubusercontent.com/assets/5615438/18478597/c0196cb6-79c9-11e6-8138-7ee2a305fd5d.jpg)

**Comment by ZeroNoRyouki** [comment]
Not cool...

That's looks like a texture problem. Benitoite is the correct ore for the End

**Comment by ZeroNoRyouki** [comment]
That was a big mix up on my part... 

Fixed
