### ISSUE TITLE
Reactor won't form.

### ISSUE THREAD

**Issue by TheOneTrueGhost** [ZeroNoRyouki/BigReactors#140]
Placing a controller or anything in the frame brings up a message saying "only frame blocks can be used in the reactor frame" placing a controller NEXT to the frame says "Air is not a valid block surrounding reactor"

So what the HELL do I do for power gen? 

playing on FTB Unstable V:2.0.3

**Comment by TheOneTrueGhost** [comment]
I'm more upset by the fact that I made enough Gelid Cryotheum to cool the damn thing and I can't even form it even with all the ports and rod controls necessary.

**Comment by ZeroNoRyouki** [comment]
First of all, calm down...

Then, from those messages (I'm guessing you are traslating them back to english) I would say that you are placing the controller on the outside of the reactor structure

The controller (or any other "device" like power ports, access ports, etc) can be placed anywere in any of the 6 faces of the reactor but not on the frame:

FFFFF
FXXXF
FXXXF
FXXXF
FFFFF

X = good
F = bad

Z

**Comment by TheOneTrueGhost** [comment]
Oh, that's an unusual mechanic to have in place. But I'm sure it makes coding easier. So, I assume the same works for a turbine? I'm trying to fill a Draconic energy sphere at super speed, and solar power isn't enough. So I plan on stepping up my game... big time. maybe I'll make reactor 2 the size of a small skyscraper.

**Comment by ZeroNoRyouki** [comment]
It's more a matter of structural integrity ...

Yes, the same is true for the turbine.
