### ISSUE TITLE
When exporting fuel, if you shift click export, the entire reactor empties fuel, but the incorrect amount of ingots is created.

### ISSUE THREAD

**Issue by marx1** [ZeroNoRyouki/BigReactors#141]
Issue:
 On larger reactors where the capacity of the reactor exceeds 64 ingots, if you hold shift when exporting fuel from a reactor it will empty the reactor, but not export the correct amount of ingots.

Steps to reproduce: 

1. Create reactor with more than 64 ingot capacity.
2. Use access port to eject fuel while holding shift.

MC version: 1.10.2
Extreme Reactors version: 1.10.2-0.4.5.30 (As included with Sky Factory 3)

Example video: https://www.youtube.com/watch?v=Mkyv0jzRFig
I shift click at this point: https://youtu.be/Mkyv0jzRFig?t=27

**Comment by ZeroNoRyouki** [comment]
This turned up to be the same problem as #127. More info there
