### ISSUE TITLE
Crashing with big reactors

### ISSUE THREAD

**Issue by Zdyzeus** [ZeroNoRyouki/BigReactors#142]
When I throw big reactors into my private modpack, I get this error: 
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Extreme Reactors (bigreactors)
There's the crash report:
[crash-2017-11-03_15.54.08-client.txt](https://github.com/ZeroNoRyouki/BigReactors/files/1442486/crash-2017-11-03_15.54.08-client.txt)
Thanks!

**Comment by ZeroNoRyouki** [comment]
You are using version 1.10.2-0.4.5.30 of Extreme Reactors. The current version is 1.10.2-0.4.5.44
Please update and try again :)

**Comment by Zdyzeus** [comment]
Didn't notice that, though I had latest version! It works now, thank you!

**Comment by ZeroNoRyouki** [comment]
Good! :)
