### ISSUE TITLE
[Reactor Suggestion] IC2-like Reactor?

### ISSUE THREAD

**Issue by Notawallplan** [ZeroNoRyouki/BigReactors#143]
Title, really. I'll elaborate.

The IC2 nuclear reactor design concept involves placing the right items in the right slots in the reactors inventory so that it produces ludicrous amounts of power with the caveat that if it is _too_ powerful, it would explode.

I wish to see a different take on the same concept. With the (basically required) change from, when the reactor goes into meltdown, literally nuking the place to simply becoming completely inoperable until all items are removed from within and the temp goes below boiling point.

Of course, i want a normal and a steam version of said reactor, and integration into IC2 (as you do.)

**Comment by ZeroNoRyouki** [comment]
I'm not sure if I understand this correctly. Are you suggesting a reactor that produce IC2 power or that I make my reactors explode when overheated? Explosion are coming...

**Comment by Notawallplan** [comment]
No. I mean a reactor that uses similar designs and mechanics to the IC2 one. Basically, an IC2 reactor that can produce RF, T, or Steam.

**Comment by ZeroNoRyouki** [comment]
I don't think it will fit in this mod
