### ISSUE TITLE
[feature request] Spent fuel extraction to Immersive Engineering Conveyor Belts, Chests, or Hoppers

### ISSUE THREAD

**Issue by stresser1** [ZeroNoRyouki/BigReactors#145]
So, I have been building a private mod pack, and I'm using all multi block structures as a theme, so Immersive Engineering features largely, but there is no EnderIO, Thermal Expansion Etc...

I have no way to remove spent fuel from the reactor other than manually... this is an issue because for some reason when no one is logged in even, the reactor is still consuming fuel. So everytime I log in, even though I'm the only one using my test server, the reactor is almost completely depleted and the extraction port is full of cyanite.

If I could use a hopper underneath the frame, or a conveyor belt to extract, or even if it would spit into a chest if it was connected directly to the port, that would be very helpful. I don't want to add a huge mod just for pipes.

**Comment by stresser1** [comment]
as I wrote the above I had an epiphany, If I can feed the reactor with a hopper I should be able to extract with one, so I put the waste port on the bottom of my reactor and placed a hopper, it works... ugly and lost my symmetry, but it works! 

Would still like conveyors to be able to extract though.

Cheers

**Comment by ZeroNoRyouki** [comment]
The Access Port transfers waste to an adjacent inventory already, but it does so only if the following conditions are met:

- the inventory support the Forge capabilities system
- the inventory does accept transfers from the side it is connected to the Access Port

So, for example, if you put a chest next to the Port, the chest will be filled with the waste produced over time by the Reactor

If I remember correctly, one time I have used a conveyor belt to feed ores from a chest to an IE Crusher and I had to put an hopper under the chest and OVER the belt to transfer the ores from the chest to the belt. So maybe the belt only accept stuff that comes from above it

Z

PS: I love the idea behind your mod pack

**Comment by stresser1** [comment]
Interesting, most IE Machines will spit into a chest or onto a belt placed on the face of a block that outputs. The belt will take the bottom of the side of the block it's placed against. I think IE looks for a chest or belt though.

I did try putting a chest on the exposed face of the output port, but it didn't output into it though, maybe I should have tried an iron chest perhaps?

You are right though, to input into a chest from a conveyor, you have to use a dropping conveyor belt on a hopper which feeds the chest, which make the conveyor system more stable than just dumping it into an open hopper.

Thanks, right now it's just me and my wife as well as a couple friends messing around in it... I added botania and blood magic to play with and one of my friends is currently ending the world so I need to find some balance there... Blood magic seems to follow my multiblock machine theme but I'm not so sure about botania... I'm not versed in them so I have to get playing with them, I've always been an engineering sort...

Also, do you know why the Reactor burns fuel even when no one is logged in? is that by design?

**Comment by ZeroNoRyouki** [comment]
No, a vanilla chest work fine (Forge add the required capability to the chest). Is the Access Port in output mode (you should see blue arrows on the port face) ?

The last time I played with Botania there were no multiblock in it (with the exception of the Elves's portal I suppose..)

Any machine in minecraft will keep running (if you leave them active/with something to do) IF the chunk(s) they are in are loaded. Chunk are loaded if they are in range of a player OR if they are forcibly loaded by what it's commonly known as a chunk loader (like the machine from ChickenChunks or FTB chunk ownership mechanism). Also note that the chunks that contains che world spawn point are also "chunk loaded" by default by minecraft

"Chunk loading" is usualy something that you do on purpose just for keeping machines running when you are not around

**Comment by stresser1** [comment]
yeah, the port was in output mode, it was filling up with cyanite, but it wasn't pushing into the chest... does it wait till it has a full stack maybe? I didn't wait until it had a whole stack, should I try it again?

Not that I really know much about it, but Blood Magic relies on Botania I thought, and the machines you build to do stuff is made of flowers n such so it's kinda multi block.

I don't think I'm too close to the spawn point... I wonder if the blood magic portal another player put in my base has a chunk loader component... it's not too far from the reactor...

**Comment by ZeroNoRyouki** [comment]
Nop, it push out every single ingots. What version of ER / Forge are you using? This is really strange. Are you using any mod that change the way chests interacts with inventories?

You have a demon portal in your base? That could turn ugly ...
If I recall correctly, the portal will automatically create the demon invasion structures around it so yeah it could be that portal that is keeping the chunks around it in memory

**Comment by stresser1** [comment]
I'm using  ExtremeReactors-1.11.2-0.4.5.30 and Forge 1.11.2-13.20.1.2386

Just went back and did it again, seems to be working this time... so I don't know. It's working now :)

The device is just a blood magic teleposer, but since it teleports instantly, it probably does keep the chunk loaded, it's probably not possible to send stuff that to an unloaded chunk.

**Comment by ZeroNoRyouki** [comment]
OK

Yup, it could be keeping both ends chunkloaded, but usally that's done only for the single chunk that the machine is in (or the adjacent ones if it lay on a chunk border). You can use a mod like MapWriter2 to see if chunks in an area are chunkloaded or now

Keep in mind that I don't keep chunks loaded when the player is not around so maybe the reactor and the chest are on different chunks, one chunkloaded and one not

**Comment by stresser1** [comment]
Not seeing that documented in MapWriter2, it's not an option in the overlays. Apparently it was in MapWriter, but that never went past 1.7 I believe.

I don't want to install chicken chunks just for the viewer, so I'll ask the guy to move the teleposer, he's not logged-in in a while though, so I may end up just breaking it.

I just looked at the chunks, a 2x2 corner of the reactor is in the same chunk as the teleposer... the chest is just to the left of the corner.

Additionally, I thought I'd dropped the spawn chunks down to 8, but in the server properties file it's still at 16... so my entire base is in the spawn chunks... FFS!

Moving it now...

**Comment by ZeroNoRyouki** [comment]
Mystery solved :)

**Comment by stresser1** [comment]
I moved the teleposer, I think it's working but the turbine dropped RPM between loads... not sure what's up with that.

Cheers
