### ISSUE TITLE
RedNet Port does not output or accept input

### ISSUE THREAD

**Issue by noahm888** [ZeroNoRyouki/BigReactors#147]
Version: 1.10.2-0.4.5.44 Beta

RedNet Port on Extreme Reactors does not seem to work
 
Setup:
ER RedNet Port:
White channel - Output energy percentage
Orange channel - Input control rod insertion
MFR RedNet cable out of port into back of MFR RedNet Controller
 
MRF RedNet Controller:
Set to Passthrough
Input set to white channel back side (I: I/O B White)
Output set to orange channel back side (O: I/O B Orange)
 
Expected Result:
Control rods insertion should match energy buffer percentage
 
Actual result:
Control rods do not change, regardless of energy levels
 
Using the MFR Meter tool on the MFR RedNet Controller yields the message "All variables are zero"

**Comment by noahm888** [comment]
Ok, I did get it to work by orienting the RedNet controller to face north and input from west and output to east. Looks like the issue is the MFR controller, not the RedNet Port

**Comment by ZeroNoRyouki** [comment]
OK
