### ISSUE TITLE
[1.12.2] Using Uranium fuel gives back Yellorium

### ISSUE THREAD

**Issue by JonasCiss** [ZeroNoRyouki/BigReactors#149]
If uranium  is placed as fuel in the reactor and you take it out again it gives you Yellorium instead of Uranium. Furthermore the inside of the reactor is rendered yellow instead of green.

**Comment by ZeroNoRyouki** [comment]
This is the intended behavior

By defualt uranium ingots (ingotUranium) are added as clones of yellorium ingots as a source of the yellorium fuel. You can disable this in the config file but then uranium will not uses as fuel unless another mod add it as such

**Comment by JonasCiss** [comment]
Can't this be added by default?
Which mod do I need then?
