### ISSUE TITLE
Dimension whitelist

### ISSUE THREAD

**Issue by jubalearly** [ZeroNoRyouki/BigReactors#15]
Can you explain how to add the mining dimension from Aroma1997 to the whitelist or any other non-vanilla dimension for that matter?

Aroma's dimensional world is dimension 6

I have tried 0 6 and 0,6 and 0, 6  Every time the mod rewrites the config back to default of just 0.

What is the proper format?

I also tried using 5 rather than 6 as I was not sure if the number should be one lower given 0 is overworld but it is stored as dim1 in the save folder.

**Comment by ZeroNoRyouki** [comment]
You need to put one Id per line, like this:

    I:dimensionWhitelist <
        0
        6
     >

Six is the correct number. <world>/dim1 is where The End is stored. The Overworld files are in the <world> directory
