### ISSUE TITLE
Nonexistent dependents  

### ISSUE THREAD

**Issue by Bobfish1335** [ZeroNoRyouki/BigReactors#150]
![why](https://user-images.githubusercontent.com/35405788/34909060-44830f46-f860-11e7-856c-58ad5617a6b9.png)
why is this happening

**Comment by ZeroNoRyouki** [comment]
My psychic powers are failing me. Please post the FML log file using a no-paste service please
Z

**Comment by ZeroNoRyouki** [comment]
Guess it's solved itself.. closing
