### ISSUE TITLE
Cyanite crafting issue (yellorite ingot and sand)

### ISSUE THREAD

**Issue by Florek81** [ZeroNoRyouki/BigReactors#151]
Hi Z,

tried to convert yellorite ingots with sand to cyanite, but it doesn't work. The config is set to true.
Is there any issue or am i missing something? And what will the recipe be?

Extreme Reactors ver. 1.12.2-0.4.5.45
![cyanite_crafting_issue](https://user-images.githubusercontent.com/35471337/34964921-925c8a34-fa50-11e7-9f4c-9e5803f8015b.png)

Thanks
Florek

**Comment by dash16** [comment]
I'm seeing this problem too, Forge 14.23.1.2607, Extreme Reactors 1.12.2-0.4.5.46

**Comment by ZeroNoRyouki** [comment]
Thank you for the report. Fixed in the next release
