### ISSUE TITLE
Occasional server crashes when controlling turbines via ComputerCraft (1.12.2)

### ISSUE THREAD

**Issue by KiskoHorst** [ZeroNoRyouki/BigReactors#153]
Crash report: https://pastebin.com/mzEHYivF
ComputerCraft program: https://pastebin.com/N1FEgNxP
Whenever the ComputerCraft program is running and the turbine is hooked up to a ComputerCraft modem the server keeps randomly crashing within a few minutes to an hour with a cryptic error message. Everything about this seems very similar to issue #111 which was supposedly fixed in a later version.

**Comment by GamesTrap** [comment]
I have the exact same issue with an OpenComputers program
Crash report: https://pastebin.com/hXPVP8KQ
OpenComputers program: https://tenyx.de/brgc/index.html#setup

**Comment by traeck** [comment]
Same Prob here:

First on MC1.10.2            OpenComputer 1.6.2.7             ExtremeReactors 0.4.5.30
later on ExtremeReactors 0.4.5.46

**Comment by ZeroNoRyouki** [comment]
Could you guys test with ER 0.4.5.45 please? (BRGC will be slow I know)

**Comment by KiskoHorst** [comment]
0.4.5.45 is the version in my original crash report

**Comment by traeck** [comment]
So far I could provoke the error with brgc. Now on version 0.4.5.45 it is really slow but so far the server did not crash.

**Comment by ZeroNoRyouki** [comment]
@traeck This seems to confirm what I guess is the problem. But @KiskoHorst was on on 0.4.5.45 from the start so we may have to problems on our hands

**Comment by citpo** [comment]
I'm also seeing the same issue after upgrading Extreme Reactors to version 0.4.5.46 (from 0.4.5.45) when using the OpenComputer application BRGC.

**Comment by ZeroNoRyouki** [comment]
@citpo : any crash with 0.4.5.45 ?

**Comment by citpo** [comment]
@ZeroNoRyouki : 
No, no crash on 0.4.5.45
OpenComputers just ran very slow with BRGC, so I tried to update.

**Comment by 616dustin** [comment]
same crash on 0.4.5.45 and 0.4.5.46

Crash Report: https://pastebin.com/Y2ZP44sL

worked with 1 reactor and 2-3 turbines.

extended to one computer with 1 reactor and 4 turbines, and another computer with 1 reactor and 2 turbines and it now crashes within minutes of server start.

**Comment by ZeroNoRyouki** [comment]
@616dustin coul you upload your world somewhere so I could grab it?

**Comment by 616dustin** [comment]
http://www.mediafire.com/file/9ump0v4tf865iop/ftb.zip

**Comment by ZeroNoRyouki** [comment]
@616dustin thank you

**Comment by ZeroNoRyouki** [comment]
Hi guys, please check #162

**Comment by ZeroNoRyouki** [comment]
ER  0.4.5.48 is out with the new computer API that should fix this crash (see #162)

**Comment by ZeroNoRyouki** [comment]
I'm closing this for the moment after the release of ER 0.4.5.48
Please let me known if something came up again
