### ISSUE TITLE
Capped Power Output

### ISSUE THREAD

**Issue by Grizzord** [ZeroNoRyouki/BigReactors#154]
i have made a large reactor with gelid cryothium. it says that it is producing around 25mil rf/t however i am only outputing around 10 mil max. i have tried every cable in thermal dynamics and mekanism and non of them even the unlimited power transfer cables will not transfer more than 10 mil. if i connect multiple cables through multiple outputs then it splits the output  into 5 mil each? i am using 1.10.2 btw

**Comment by ZeroNoRyouki** [comment]
The Power Taps themselves have no power transfer limit, what you are hitting is the internal power buffer size (10M RF). The generated energy is put in the buffer and any excess is lost and from there it goes to the Power Taps.

So, basically, the maximum amount of energy you can get from any-size reactor is 10M RF/t

This maybe or maybe not change in future versions, who knows :)
