### ISSUE TITLE
Add oredict entries to ores

### ISSUE THREAD

**Issue by bochen415** [ZeroNoRyouki/BigReactors#156]
As title.
Anglesite and Benitoite ores don't have an oredict key added.

**Comment by ZeroNoRyouki** [comment]
Are there any other mods that add them? Or you need them for generic recipes?

**Comment by ZeroNoRyouki** [comment]
Added to the next release

**Comment by bochen415** [comment]
I specifically need those for `/oredistirbution` command from [BDLib](https://github.com/bdew/bdlib) to work properly and ofc for [Mekanism's](https://github.com/aidancbrady/mekanism) Digital Miner support so those can be mined with an `ore*` filter used in this machine.

**Comment by ZeroNoRyouki** [comment]
Uhm that's something I don't like to be happening. Anglesite and Benitoite are hard to find because I want them to be hard to find

**Comment by bochen415** [comment]
Won't change anything, players will find a single ore block and use it in the filter anyways.
IMHO all ores should be oredicted but that's just me.
