### ISSUE TITLE
RPM on Turbine state 0 and blades dont spin but is producing rf.

### ISSUE THREAD

**Issue by Nicon4454** [ZeroNoRyouki/BigReactors#157]
using ExtremeReactors-1.10.2-0.4.5.46
2511 forge

RPM on Turbine state 0 and blades don't spin but it is producing rf.

**Comment by Tahakk** [comment]
Can you provide screenshot of your turbine GUI please? Just to be sure you have the right buttons selected :)

**Comment by Nicon4454** [comment]
yes 
here is the image:
http://prntscr.com/ig9xem

**Comment by Nicon4454** [comment]
Any Idea what is wrong?

**Comment by Tahakk** [comment]
no Idea, and my apologies, 1st time I read that your blades are spinning and you are not getting RF. I'll leave it to mod author

**Comment by Nicon4454** [comment]
is there a fix for this?

**Comment by ZeroNoRyouki** [comment]
I can't really reproduce this... Could you show me your turbine? What other mods are there in your pack?

**Comment by ZeroNoRyouki** [comment]
Closing. If you still have problems please reply below
