### ISSUE TITLE
Turbine

### ISSUE THREAD

**Issue by ShaCraft** [ZeroNoRyouki/BigReactors#16]
I'm looking to do a mod spotlight on Extreme Reactors but I have some questions. 

Is there only one fluid port for Reactor to turbine now? Or is Turbines not ready yet?

The rotor blades in the turbine look funky but the reactor works. 

=S=
RG_Sha

**Comment by ShaCraft** [comment]
Also if you build a 32x32x48 reactor the lag factor is nuts. I also can not get back into my test world to finish my Spotlight. lol

So I'm just going to advise my viewers to only make a reactor as big as they need for now and not see how big of one they can make.

**Comment by ZeroNoRyouki** [comment]
Hi and thank you for the spotlight

We known that there are some glitch in the rotor rendering on some graphics cards. Could you tell us the model of yours?

Could you post your world somewhere so I can grab it and check what's going on? Are you talking about TPS lag or FPS lag?

Also, are you using the last version of ER ?

Thank you!
Z

**Comment by ShaCraft** [comment]
Yea I am using R290x cards. I have the saves for the world I think. Let me find a place to drop them and I'll send you a link to the zip. As for the version, I used ExtremeReactors-1.10.2-0.4.5.15. I think that is the current version and the one that WhatTheDrunk is using in ALL THE MODS (the pack I am using for most stuff).

**Comment by ShaCraft** [comment]
Here is a link to the world save
https://www.dropbox.com/s/dz87rpbclu7zgpr/Reactor%20testing%20and%20spotlight.rar?dl=0
