### ISSUE TITLE
Suggestion- Fussion Reactors+ More

### ISSUE THREAD

**Issue by CTH999** [ZeroNoRyouki/BigReactors#160]
It would be nice if this had fusion reactors, and maybe particle accelerators as well. However, that's just my thought. Also, the fusion reactor could be used to create steam, and then use it in a turbine. Also, it would be nice if it could produce other materials. For a lot of first materials!

However, this is just a suggestion. It's your mod, and your decision.

**Comment by ZeroNoRyouki** [comment]
Thank you for your suggestion. For the moment adding another type of reactor is not in my plans but never say never

**Comment by Saklad5** [comment]
If you are not planning on adding new reactor types in the near-future, you should consider removing the [Legacy] suffix from blocks.

**Comment by CTH999** [comment]
@Saklad5 I personally partly agree, but I think it would make sense to leave it, to hint that more is coming...

I completely understand, You want to get it working before you add in mod-breaking featueres:)

Also, just don't forget about the cyanite multiblock... eventually!

Can't wait!
