### ISSUE TITLE
Tick Issue

### ISSUE THREAD

**Issue by Explosivee** [ZeroNoRyouki/BigReactors#161]
Minecraft Version: 1.12.2
Modpack: FTB Revelation v1.6
Mod Version: ExtremeReactors-1.12.2-0.4.5.46.jar

Issue:
Ractors makes massive lag in my server because every reactor part etc count as entitie one max sized reactor make the TPS 3 from 13, you should check that thing, it was okay in old version but in this one it makes massive lag.

My server's hardware;
i7 7700K OC (5 GHz)
64GB 2400 MHz RAM
x2 480GB NVMe
1 Gbps Internet

**Comment by ZeroNoRyouki** [comment]
Every reactor block has a TileEntity (they are not Entities) but almost none of them are ticking TileEntities so they don't consume tick time. How big exactly your reactor is and how many fuel rods you have in there?

**Comment by Explosivee** [comment]
https://goo.gl/Eun8ZD Someone made 3 of this and it killed the server

**Comment by scollenburg** [comment]
That's reactor design problem, not a "mod" problem. The design I use can generate 516 RF per rod, compared to 151 RF/rod for the design posted by Explosivee.

Perhaps a parameter allowing server admins to set a maximum number of active fuel rods per player? If when "checking" the reactor before powering up if the max is hit, the reactor won't "make". The 16x16x46 design I use generates 379k RF/t using 736 fuel rods, so even if you wanted to let players hit the 1m/tick number 5000 rods would be more than enough. Single player the max could be set to an obscene number (or if desired by pack authors, a paltry number to force players to find other more creative solutions).

**Comment by ZeroNoRyouki** [comment]
OK so, I've build one reactor following that design. I've not yet filled it completely with liquid ender but so far I'm still rocking at 20 TPS. The reactor update-cycle is taking less and 1% of the tick time:

[03] |   |   |   Zero CORE|Multiblock|Tick - 0.82%/0.76%
[04] |   |   |   |   Extreme Reactors|Reactor update - 89.75%/0.68%

Let's see if that much flowing fluid could be the problem here..

**Comment by ZeroNoRyouki** [comment]
I've just released 0.4.5.48 and it come with some optimization on fuel updates that will lower even more the tick time used by the reactor
I've also optimized the fuel rods rendering so your users should have a better FPS on their clients while looking at huge reactors

**Comment by Explosivee** [comment]
Thank you man, good job

**Comment by ZeroNoRyouki** [comment]
@Explosivee you are welcome. Have you tested the new version on your server?

**Comment by Explosivee** [comment]
@ZeroNoRyouki I'm having legit 20TPS with +15 online players in 2 months old map, FTB Revelation v1.8 so yea, it looks good

**Comment by ZeroNoRyouki** [comment]
Good! :)
