### ISSUE TITLE
Reactor Redstone Control Port Won't Disable Reactor

### ISSUE THREAD

**Issue by adamjkoch** [ZeroNoRyouki/BigReactors#163]
I am using FTB Direwolf20 1.12.2 modpack version 1.10 (Beta), which uses ExtremeReactors version 1.12.2-0.4.5.46 and Forge version 14.23.2.2627. On my server, I am attempting to use a daylight sensor to only run the reactor at night (solar panels handle daytime). To send the redstone signal to the port I am using Integrate Dynamic Redstone Reader to read the sensor's output, and then it sends it to a Redstone Writer which is connected to the control port. If the reactor is disabled and then it turns to night, it will turn the reactor off. However, if it is running and becomes daytime, it does not disable the reactor. I have also noticed similar behavior when connecting a lever directly to the port itself. It does not always seem to "listen" to the signal being inputted. 

If you need additional information, please let me know.

**Comment by ZeroNoRyouki** [comment]
I've testing this in that pack with a simple lever and it's working as designed.
 
Keep in mind that the Redstone Port do it's thing (for the "Input" settings) when it's notified by MC that something has changed in the block it is facing. It's not checking that itself every tick for performance reasons

So, if you have an "off" lever connected to the port (directly or with some redstone dust) and you turn on the reactor manually, the reactor will stay on. If you change the lever status (off -> on) the redstone port will notice that and will keep the reactor on. If you change it again (on -> off) the port will turn off the reactor

**Comment by adamjkoch** [comment]
I am familiar with how it is supposed to work. See the screenshot of my setup (https://i.imgur.com/ONkFDHs.png). The Integrated Dynamics Redstone Reader (it is set to read Redstone Low) is correctly reading the output from the Vanilla daylight sensor, and it will turn on the reactor. The problem is when it gets light, and the Redstone Writer will write false to the Redstone Port, but the reactor does not turn off. If I change the port to another redstone function, and then put it back to turn the system on/off and the reactor will turn off.

There is clearly something going on, and it must be with the reactor port. I use this exact same setup on other machines and it turns on and off as expected. The reactor is the only one that does not seem to work properly.

**Comment by ZeroNoRyouki** [comment]
Hi, sorry for the delay

I've re-tested it using your setup. With and without the TD pipes, using "redstone" and "redstone low" as the variables. And it works fine :(

![2018-03-31_18 09 13](https://user-images.githubusercontent.com/7107662/38165119-d47cdc9a-350e-11e8-8c2c-08f9ff84e382.png)
![2018-03-31_18 09 17](https://user-images.githubusercontent.com/7107662/38165120-d497039a-350e-11e8-9c0d-5fd1f4b50957.png)
![2018-03-31_18 09 50](https://user-images.githubusercontent.com/7107662/38165121-d4adb040-350e-11e8-8b6f-2faf9b01de32.png)
![2018-03-31_18 09 58](https://user-images.githubusercontent.com/7107662/38165122-d4c51ed8-350e-11e8-9a47-b4c61b576981.png)
![2018-03-31_18 10 18](https://user-images.githubusercontent.com/7107662/38165123-d4ddf20a-350e-11e8-903e-35bca043d728.png)

As you can see, when the daylight sensor is emitting a redstone signal the reactor (and the redstone lamp) is off. When there is no signal the reactor (and the lamp) is on

**Comment by ZeroNoRyouki** [comment]
Hi, are you still experiencing this problem?

**Comment by ZeroNoRyouki** [comment]
Closing. If you have any other problem please replay below
