### ISSUE TITLE
Crash after update [MC1.12.2]

### ISSUE THREAD

**Issue by kellixon** [ZeroNoRyouki/BigReactors#164]
New ExtremeReactors+ZeroCore causes crash All "ThermalMods".
Minecraft: 1.12.2
Forge: 14.23.2.2640
ExtremeReactors 0.4.5.48
ZeroCore 0.1.2.0
Crash reports - https://pastebin.com/RPCZ51FG

**Comment by ZeroNoRyouki** [comment]
Dup of https://github.com/ZeroNoRyouki/ZeroCore/issues/21
That package should not be there..

**Comment by ZeroNoRyouki** [comment]
Fixed with Zero CORE  0.1.2.1
Thanks for the report
