### ISSUE TITLE
[1.12.2] Uranium/Yellorium Exchange in Fuel Port

### ISSUE THREAD

**Issue by Yhuxz** [ZeroNoRyouki/BigReactors#165]
Try to use uranium ingot from Immersive Engineering as fuel and place it in the input slot, now press eject fuel and it ejects yellorium ingot instead.

**Comment by Yhuxz** [comment]
#126

**Comment by ZeroNoRyouki** [comment]
This is the correct behavior under the default settings

Immersive Engineering register it's uranium ingots as ingotUranium in the Ore Dictionary (like many other mods do)

Under the default configs (autoAddUranium), ER treat all ingotUranium as yellorium and a source of the yellorium fuel. As the fuel inside the Reactor is yellorium, you will get back yellorium ingots

Please note that if you disable the autoAddUranium config option, another mod need to add it's uranium as a fuel to the Reactor to it be accepted
