### ISSUE TITLE
[1.12.2] Error 404: Not_working

### ISSUE THREAD

**Issue by Yhuxz** [ZeroNoRyouki/BigReactors#168]
What gives?
![what gives](https://user-images.githubusercontent.com/36140746/38389899-54ffb2d8-3952-11e8-9b20-58e702214a9e.png)

Forge: 1.12.2-forge1.12.2-14.23.2.2611
Extreme Reactors: 1.12.2-0.4.5.48.jar
Zero Core: 1.12-0.1.2.1.jar

**Comment by ZeroNoRyouki** [comment]
Could you send me the FML log using a nopaste service please ?

**Comment by Yhuxz** [comment]
https://gist.github.com/Yhuxz/7453341d85a3e250378e64f353d06358

**Comment by ZeroNoRyouki** [comment]
There is something wrong with your copy of the Zero CORE jar: 

[02:00:33] [main/ERROR] [FML/]: Unable to read the jar file zerocore-1.12-0.1.2.1.jar - ignoring
java.util.zip.ZipException: zip file is empty

Re-download it please

**Comment by Yhuxz** [comment]
Yep I suppose to tell you that earlier but Im distracted on Ender IO's Beta release on 1.12.2

![lmaorofl](https://user-images.githubusercontent.com/36140746/38452220-42ac8554-3a72-11e8-879f-4a30024f3d88.png)

**Comment by ZeroNoRyouki** [comment]
OK. Case closed then
