### ISSUE TITLE
oversized reactor not completing multiblock

### ISSUE THREAD

**Issue by flanigomik** [ZeroNoRyouki/BigReactors#169]
on my 1.12.2 server running ExtremeReactors-1.12.2-0.4.5.48 we have a over-sized reactor, (15x15x71) the server config has been changed to allow for such a reactor, it is set up to power turbines which are directly connected. when the reactor is completed the multiblock never visually completes, the reactor is usable if the controller is right clicked and you can put things in and take things out but it shows that is always making 200rf/t despite the temperature or radioactivity of the reactor, it does not show any water level indicator or fluid info however the connected turbines are getting steam and working properly

**Comment by ZeroNoRyouki** [comment]
Could you show me a pic of your setup please?

**Comment by flanigomik** [comment]
i put together a little gallery here https://imgur.com/a/uevEy

**Comment by flanigomik** [comment]
any ideas?

**Comment by flanigomik** [comment]
server pack is called Ram destroyer (cause it is Ram heavy) and can be found on the technic launcher using this link https://www.technicpack.net/modpack/ram-destroyer.1207587 is there a way i can directly send you the server IP? rather not have a whole bunch of randoms joining XD.

**Comment by ZeroNoRyouki** [comment]
I'll check it, thank you

Did you have any luck with the screenshot?

**Comment by flanigomik** [comment]
yes, litterally just took them lol https://imgur.com/a/IL2qL

**Comment by flanigomik** [comment]
if you need anything else i am currently standing directly in front of the reactor, i can get whatever data you need

**Comment by flanigomik** [comment]
do you maybe have a discord or something  a bit easier to communicate with?

**Comment by ZeroNoRyouki** [comment]
ok, it's not a graphical glitch, it's actually disassembled. If you right click on any block it should give you an error message. What does it say?

**Comment by ZeroNoRyouki** [comment]
what happen if you break a casing block and then replace it?

**Comment by flanigomik** [comment]
issue persists, gives an error when right clicked with the missing block but no error and behaves as in the video when re completed

**Comment by flanigomik** [comment]
also it should be noted that the connected computercraft terminal does display the amount of fluid in the reactor correctly, however the controller does not display fluid at all

**Comment by ZeroNoRyouki** [comment]
ok, this is all very perplexing. could you please send me your world so that I could load it in my debug enviroment?

**Comment by flanigomik** [comment]
yes i can, having said that i don't know if the world will be stable outside my pack... there are a lot of mods and it might be one of them causing it

**Comment by flanigomik** [comment]
as we have the config changed to allow for a reactor of this size will you want that as well?

**Comment by ZeroNoRyouki** [comment]
Yup, thank you

**Comment by flanigomik** [comment]
would you also like the other mods and their configs for testing?

**Comment by ZeroNoRyouki** [comment]
I will download the original pack, but yes, grab the whole config folder so I can be sure to replicate things correctly

**Comment by flanigomik** [comment]
ok, a thing to note, we have removed the Sync mod from the server but not from the client pack download becasue it was causing crashes, if you do not remove it from the mods folder before opening the world it will crash when you enter chunks around the reactor

**Comment by flanigomik** [comment]
i'm pushing an update that will do it from my end in a few minutes

**Comment by flanigomik** [comment]
i pushed the update so if you download it now from the link above all will work, you will still want to use the custom configs provided though, will have that for you with the world in about 3 minutes, just waiting for dropbox to upload

**Comment by flanigomik** [comment]
and here is the world and config https://www.dropbox.com/s/jinv8x2t3cew47d/serverworld.7z?dl=1

**Comment by flanigomik** [comment]
forgot to say the exact coords of the reactor are 202 79 38, that is probably important to you :P

**Comment by ZeroNoRyouki** [comment]
Yes :)

Thank you, downloading right now

**Comment by ZeroNoRyouki** [comment]
Ok so, first run from technic:

![2018-04-13_12 09 48](https://user-images.githubusercontent.com/7107662/38729587-c3766858-3f13-11e8-8151-79493a275c77.png)


![2018-04-13_12 10 09](https://user-images.githubusercontent.com/7107662/38729588-c39cd81c-3f13-11e8-86a9-4ed430c21b40.png)

Just teleported in. So far the only thing I did is remove the ping mod cause I keep getting crashes from the load screen

Stanger and stranger

**Comment by flanigomik** [comment]
very weird, if you want you can join my server and look at the actual thing

**Comment by flanigomik** [comment]
you will still be able to join without the ping mod, here is the IP 50.67.181.249

**Comment by flanigomik** [comment]
no problem, would be hugely supprised if it is, a shot in the dark though could it be caused by the client config having a smaller max size than the server config? seems crazy but maybe?

**Comment by ZeroNoRyouki** [comment]
I replaced the whole config folder with the one from your archive

**Comment by flanigomik** [comment]
which is the one the server is using but the clients are using the default generated one

**Comment by ZeroNoRyouki** [comment]
Ah, your clients are using the default one. Yes that could be it

**Comment by flanigomik** [comment]
doesn't explain why the block state would still show inactive though does it?

**Comment by flanigomik** [comment]
i am restarting with the modified config and will update you, i will be annoyed if that is it :P

**Comment by ZeroNoRyouki** [comment]
It does, actually. That particular "state" is not persisted in the actual blockstate that it is saved in the world data and tracked by the server. It's basically client side-only

**Comment by flanigomik** [comment]
huh... well give me a minute and i will confirm, this might be a user error

**Comment by ZeroNoRyouki** [comment]
I'm restarting too with the default config in place

**Comment by flanigomik** [comment]
of course when i am trying to test this the game takes longer than normal to load :D

**Comment by flanigomik** [comment]
so swapping the config DID in fact rectify this issue... can't believe i didn't try that... so i guess as a suggestion the server should either 

1 send the config to the client
2 warn about this issue in config
3 warn about this issue when joining in chat
4 refuse connection

**Comment by ZeroNoRyouki** [comment]
Nowadays mod packs come with the relevant configs  included so that could be an option too. It's basically the main reason why I did not add some synchronization to ER when I first ported the code of Big Reactor. Otherwise I would say 1 or 3

**Comment by ZeroNoRyouki** [comment]
You will have the opposite situation: a fully formed reactor on  the client that do nothing because it's not assembled on the server side

**Comment by flanigomik** [comment]
well today i learned! good night and good luck with whatever changes you choose to make.

**Comment by ZeroNoRyouki** [comment]
Thank you! And good night ;)
