### ISSUE TITLE
Un-hardcode/Remove Reactor coolant tank 50 000 mb limit

### ISSUE THREAD

**Issue by roboderpy** [ZeroNoRyouki/BigReactors#170]
Because when reactor becomes big, you are forced to use it as passively cooled reactor because of 50 000 mb tank size limit

**Comment by ZeroNoRyouki** [comment]
Like I've said many times, this is a balancing factor. If you need more steam you have to build more Reactors

**Comment by roboderpy** [comment]
So split one reactor into 15 reactors just for one industrial turbine?

What do stop you from adding conflig option for this?

**Comment by ZeroNoRyouki** [comment]
Balancing. If I add such a config option it will always used to make a single reactor power an unlimited amount of turbines. In your example, this will not only break ER internal balancing, it will break Mekanism too

**Comment by roboderpy** [comment]
Mekanism has Fusion Reactor which i has disabled because of its "balance" (giga redstone flux out of water). We got 4 million yellorium stored and i really want to burn it in active cooled reactor. 

And how can this break mekanism's balance? One industrial turbine consume thousands of steam buckets per tick when ER's only two buckets per tick at max.

**Comment by Tahakk** [comment]
And how about building more trubines, in my SkyFactory world I had over 100 of them, it worked like charm.

**Comment by roboderpy** [comment]
100 turbines -> near 3 MRF/t. This is so small number for me, even on midgame. My basement consumes like 8 MRF/t

Anyway, extreme reactors doesn't work for me anymore because zerocore doesn't properly handle multiblock structures, so reactor doesn't form on CubicChunks world.

Have a good turbine.
![javaw_2018-04-15_15-43-08](https://user-images.githubusercontent.com/6339511/40648885-b645fa3a-6359-11e8-9d56-95ab97c0d5b2.png)
![javaw_2018-04-15_15-40-27](https://user-images.githubusercontent.com/6339511/40648886-b6acf0f0-6359-11e8-89d4-fd6d7ff368e8.png)
![javaw_2018-04-15_15-47-16](https://user-images.githubusercontent.com/6339511/40648893-b9aba116-6359-11e8-80b7-ee6bcd86b615.png)

**Comment by Tahakk** [comment]
If your base have so much power consumption maybe you should consider rebuilding it or using additional ways of generating RF.

btw. what the *f* is taking that much RF

**Comment by roboderpy** [comment]
RFTools dimensions + Mekanism factories. I play Minecraft in Factorio style.

**Comment by Tahakk** [comment]
Then you have no problem building more turbines. Easy as that. As this is not bug, you should close this issue ;)

**Comment by ZeroNoRyouki** [comment]
> Anyway, extreme reactors doesn't work for me anymore because zerocore doesn't properly handle multiblock structures, so reactor doesn't form on CubicChunks world.

That's a problem on CubicChunks side, not mine

**Comment by roboderpy** [comment]
![discordcanary_2018-05-29_16-36-47](https://user-images.githubusercontent.com/6339511/40650876-7da15d6e-635e-11e8-809e-d71109da8ef1.png)

**Comment by ZeroNoRyouki** [comment]
Check it's issues page ...
