### ISSUE TITLE
Reactor Coolant Ports not accepting water

### ISSUE THREAD

**Issue by rgtexa** [ZeroNoRyouki/BigReactors#18]
Using 0.4.5.15, I am unable to put water into an actively cooled reactor.

Playing All the Mods pack (v1.24), I've tried Ender IO Fluid Conduits (with an Ender IO Reservoir), Mekanism Mechanical Pipes (with Mekanism Pumps over an infinite source), and Extra Utilities 2 Pipes (with a liquid transfer node and mining and speed upgrades over an infinite source), and none will insert water into the reactor.

All pipes render as connected, but none will insert. I've also ensured they were configured correctly (if necessary, for example, Ender IO fluid conduits were set to extract, always active on the reservoir side and insert only at the reactor coolant port side, and Mekanism pipes were configured for push mode at the reactor side).

Reactor is 9x9x9 with 9 fuel rods and graphite blocks for interior fill. I have 2 access ports (one insert, one extract), the controller, and an RF power tap on one side, and the 2 coolant ports (one configured for insert, one extract) on another side. All other side blocks are reactor casing. Here is a link to the [reactor configuration](http://br.sidoh.org/#reactor-design?length=7&width=7&height=7&activelyCooled=false&controlRodInsertion=0&layout=10GX5GXGX3GXGXGX3GXGX5GX10G) as built. The coolant ports would be located in the left side, and the controller, power tap, and access ports in the bottom side.

The reactor forms correctly, and the UI updates to the actively cooled UI showing the cold and hot tanks.

**Comment by ZeroNoRyouki** [comment]
It look like an UI-update problem, I'm getting steam out of the reactor using Ender IO conduits

![2016-09-16_17 24 21](https://cloud.githubusercontent.com/assets/7107662/18591353/8d1dfb9a-7c32-11e6-86de-b2f7ed1efca8.png)

**Comment by ZeroNoRyouki** [comment]
The fix will be included in the next release of the mod
