### ISSUE TITLE
ExtremeReactors-1.12.2-0.4.5.49 (forge version issue)

### ISSUE THREAD

**Issue by unown294** [ZeroNoRyouki/BigReactors#181]
It appears that the newer version of this mode requires an older version of forge for some reason, said i needed Forge@[12.18.3.2511]

attached is the crash report for further investigating
[crash-2018-06-17_17.42.49-server.txt](https://github.com/ZeroNoRyouki/BigReactors/files/2109497/crash-2018-06-17_17.42.49-server.txt)

**Comment by ZeroNoRyouki** [comment]
The Forge version is correct. You have downloaded the 1.10.2 jar
