### ISSUE TITLE
???

### ISSUE THREAD

**Issue by mstfemirkynr** [ZeroNoRyouki/BigReactors#185]
The game crashed whilst initializing game
The game crashed whilst initializing game
Error: java.lang.IllegalArgumentException: Block: class erogenousbeef.bigreactors.common.multiblock.block.BlockMultiblockController has property: controller with invalidly named value: �dle

**Comment by Tahakk** [comment]
Post your mod list and whole crash log if possible, also **???** title isn't really descriptive. If you want some support you have to put effort into it

**Comment by ZeroNoRyouki** [comment]
@mstfemirkynr do you have more info on this?

**Comment by ZeroNoRyouki** [comment]
Closing for now. Feel free to add more info below if you have them
