### ISSUE TITLE
Oversize turbines not forming mulitblock

### ISSUE THREAD

**Issue by HFinner** [ZeroNoRyouki/BigReactors#186]
Hi! I am aware that you have a size limit on the mod for turbine shells, and I decided that I wanted to make a big one, precisely 19x13x13 (LxWxH) to make it look nice. I went into my server config and went into extreme reactors and changed the turbine sizing from their defaults to 100 for x, y, and z. The issue is, when I finish building it, nothing happens. If I right click on the turbine it doesn't say anything and it even lets me access the controller. I am able to build smaller turbines with the exact same setup and they form a multiblock, unlike mine. 

And what's funny about it, is it allows me to use the controller and accept air and push out water. It also creates energy but SLOWLY because the only thing not working in the turbine is the fan itself which is the whole point. It also says rotor speed of 0 RPM (with 48 blades placed) just so you know. I guess I will just shorten my turbine casing by a few blocks but just wanted you to know that in my case, the multiblock will not form even though the server allows for it with size in mind. Thanks!

**Comment by ZeroNoRyouki** [comment]
You should modify the client config too

**Comment by ZeroNoRyouki** [comment]
Closing this for now. If you have any other problems please add them below
