### ISSUE TITLE
Extreme Reactors Not Recognizing Forge Version As Above Requirements

### ISSUE THREAD

**Issue by darth-crunchus** [ZeroNoRyouki/BigReactors#189]
"You must include the right dependencies for Extreme Reactors:
Requires Forge 12.18.3.2511 or above (missing)"

I'm using Forge 14.23.4.2747

**Comment by ZeroNoRyouki** [comment]
You downloaded the 1.10.2 version of ER

Please check the name of the jar before downloading it (or use the Curse/Twitch Client)
