### ISSUE TITLE
[1.10.2] [Bug] Localization of Ore tiles is wrong

### ISSUE THREAD

**Issue by SnowShock35** [ZeroNoRyouki/BigReactors#19]
Hello,

I've got an issue to report regarding Extreme Reactors, here's the details. . .

### Important Information

* Minecraft 1.10.2
* Minecraft Forge 12.18.1.2092
* Extreme Reactors 1.10.2-0.4.5.15
* ZeroCore 1.10.2-0.0.8.0
* Other mods used: 
    * The One Probe 1.10.1.1.1
    * Waila 1.7.0-B3_1.9.4

### Issue Description

The One Probe incorrectly defines `Anglesite Ore` and `Benitoite Ore`. This does not happen for the other mod blocks that have Metadata values nor does it occur with Waila. 

So this is a rather odd issue and I'm unsure why it's caused. I've thought about reporting this to @McJty but, the issue is **not** persistent with the One Probe on other blocks that are registered with metadata so I believe it to be an issue with the ore blocks themselves and how their textures and tile names are registered and the one probe then getting confused because of that (My guess is that Waila doesn't have this problem as it detects them differently).

I've provided some screenshots as explaining it more clearly as explaining this issue is rather difficult to some degree.

### Media

![Issue Screenshot #1](http://ss.snowshock35.com/2016/09/1474209550-963a4e61.png)
![Issue Screenshot #2](http://ss.snowshock35.com/2016/09/1474210054-12ec422c.png)
![Issue Screenshot #3](http://ss.snowshock35.com/2016/09/1474210114-5ce0ce93.png)

I will make @McJty aware of this bug report just in case it happens to be his mod.

**Comment by McJty** [comment]
To solve this this mod has to implement getPickBlock correctly. That's what The One Probe uses to see what a block is

**Comment by ZeroNoRyouki** [comment]
Thank you for the report.

The fix will be included in the next release of the mod

**Comment by SnowShock35** [comment]
No problem, thanks for the quick fix 😄
