### ISSUE TITLE
Max Power Output is 1000k rf/t (not enougt)

### ISSUE THREAD

**Issue by ICSubiX** [ZeroNoRyouki/BigReactors#190]
I try to fill up the Drconic Core Tier 8 in survival, therfor i need a mod to output a lot of rf/t. In the config is the "powerProductionMultiplier" so i added a couple 0's . Now the TurbineContoler say that it`s generating over 1Peta rf/t but still outputig only 1M /t. (ther are enougt poweroutputs installed, some aren't even used) (the energy bar in the controler is NOT filled up!)

So the question i have is if ther is any way to upgrade the Code to Output More than 1M/t ?
It would be awsome if you could change the "powerProductionMultiplier" and the MAXoutput changes in the same way. (so i can putput all the energy)

BTW: I absolutly appreciate all the time you spend in modding. THANKS a lot!

Minecraft Version: 1.12.2 Mod: 0.4.5.49

(and yes instead of iron for the craftig recept i use Infinity ingots => Big/extrem reactors are VERY late game :D)

Greedings form Germany
IC_SubiX

**Comment by ZeroNoRyouki** [comment]
You have to build more Turbines/Reactors. Each is limited (by design) by it's internal energy buffer

**Comment by ICSubiX** [comment]
> 
> 
> You have to build more Turbines/Reactors. Each is limited (by design) by it's internal energy buffer

jea, so far i built 64 x 32 (with a Rftools Builder) but 2k Turbines are quite laggy

Thanks anyway

**Comment by ZeroNoRyouki** [comment]
If you are experiencing frame lag with that many turbines you could disable the rotor animation in the config file or by building the turbines without glass
