### ISSUE TITLE
Reactor Multi-block cannot form - Wanting block outside of reactor to be a Reactor Casing

### ISSUE THREAD

**Issue by noea4** [ZeroNoRyouki/BigReactors#195]
I'm currently running the FTB Revelation modpack ver. 2.7.0. I'm attempting to form a 3x3x3 Reactor multi-block. However when I complete the structure the multi-block does not form and checking the reactor controller by clicking on it, it gives me the message:

-259, 63, 76 - Only Reactor Casings can be used here

My reactor does not go above Y-level 62, so this message makes absolutely no sense. Looking at one of the casings in F3 shows that:

bigreactors:reactorcasing
casing: single
type: legacy

I'm not sure what to make of this message. Any ideas?

**Comment by ZeroNoRyouki** [comment]
Could you post somewhere a picture of your reactor?

That error message is emitted when a block that is not a Reactor Casing on the other side of a Fuel Rod (from top to bottom, for example, you should have a Control Rod, any number of Fuel Rods and a Casing block)

**Comment by ZeroNoRyouki** [comment]
Any news on this?
