### ISSUE TITLE
No Yellorium Ingots, or Yellorium Ore

### ISSUE THREAD

**Issue by CakeArmy** [ZeroNoRyouki/BigReactors#197]
Howdy, I'm using FoolCraft 3 as a base, I then went and added Extreme Reactors & ZeroCore, both on the latest version as of 2/10/19. There is no yellorium ingots or ore in either JEI or the creative inventory. I saw another issue from September of '17 however that appears to be extremely outdated. Here is a screenshot:

![image](https://user-images.githubusercontent.com/13841599/52538746-276fe900-2d2b-11e9-81c8-d66458091a2d.png)

**Comment by CakeArmy** [comment]
Just wnat to verify, yellorium was removed, correct?

**Comment by ZeroNoRyouki** [comment]
No, Yellorium was not removed from the mod
