### ISSUE TITLE
[Addon Issue] It seems that I can't add anything

### ISSUE THREAD

**Issue by EmosewaPixel** [ZeroNoRyouki/BigReactors#198]
I'm going to keep this short. I'm trying to add reactor fuels through a custom mod. Looking at your code, everything should be registering, but when I go into the game it doesn't seem like it has: https://github.com/EmosewaPixel/PixelUtilities/blob/8cce5b7bddfb157f043a7d21d389556b671d6732/src/main/java/com/EmosewaPixel/PixelUtils/PixelUtils.java#L33 
There also are no errors to be found in the console. While I did look through it 5 times, I wouldn't be too surprised if I've missed something on my side.

P.S. Ik the way I deal with items is weird, but it's what I use as a replacement for meta data, as I'm going to be using this mod in future MC versions

**Comment by ZeroNoRyouki** [comment]
Check this for an example of what you are trying to do:

https://github.com/joserobjr/UraniumBigReactor/blob/master/src/main/java/br/com/gamemods/ubr/UraniumBigReactorMod.java

**Comment by EmosewaPixel** [comment]
I already did before opening this issue.

**Comment by ZeroNoRyouki** [comment]
You need to register your reactants in the Ore Dictionary

**Comment by EmosewaPixel** [comment]
Why would that be the case when I'm using item stacks for reactants and not ore dictionary entries?

**Comment by ZeroNoRyouki** [comment]
Because reactants are registered by name, not itemstacks (Reactants::registerReactant)

You than map something (an item in your case) to a reactant (Reactants::registerSolid)

And because this allow thigs from different mods to map to the same reactant

**Comment by EmosewaPixel** [comment]
Ok, taking another look at the code, I get what you mean now. So reactants are always mapped to an ore dictionary entry, when you set an itemstack it just maps it to the entries that stack is part of. Thanks.

**Comment by ZeroNoRyouki** [comment]
Sorta. With Reactants::registerSolid you register a source for a given reactant (something I can use to make the reactant), using the Ore Dictionary name to link the two

Don't worry, no trouble at all
