### ISSUE TITLE
Kinesis Pipe issue

### ISSUE THREAD

**Issue by avr6ude** [ZeroNoRyouki/BigReactors#199]
Minecraft 1.12.2, Extreme Reactors Beta 1.12.2-0.4.5.65 
Basically, if I connect Wooden Kinesis Pipe from BC3 to RF Power Tap it doesn't work. It did work in the original mod just fine.

**Comment by ZeroNoRyouki** [comment]
Buildcraft don't support RF power anymore so it's pipe can't connect to RF producers

**Comment by avr6ude** [comment]
> Buildcraft don't support RF power anymore so it's pipe can't connect to RF producers

so is there CapabilityEnergy support coming any time soon?

**Comment by ZeroNoRyouki** [comment]
If you are talking about the Forge Power API on my end, that's already there. It's what the Redstone Flux Power Tap is using to connect to other blocks
