### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by ProsperCraft** [ZeroNoRyouki/BigReactors#20]
We are having major performance issues with Zero core and Enderio conduits.

https://timings.aikar.co/v2/?id=1f2418ebd4ce40a48bd639c53a9494b0

Modpack - Allthemods

Minecraft Version- 1.10.2

zerocore-1.10.2-0.0.8.0
EnderIO-1.10.2-3.0.1.107_beta

**Comment by ProsperCraft** [comment]
Here is a warmroast report

https://gyazo.com/67a627aa69c17d3b57a857d6c5ac3dc4

**Comment by ZeroNoRyouki** [comment]
Sorry for the delay.

I've testing this with 11 reactors all connected, via conduits, to a big capacitor bank. It's clocking at 7 ms / 20 tps

Are you sure that there is nothing around breaking and replacing some conduits somewhere?

**Comment by HenryLoenwind** [comment]
BTW: Did you try with build 107 or newer? Makes kind of a huge difference as build 108 replaced the complete energy handling code of Ender IO...

**Comment by ZeroNoRyouki** [comment]
I've used build 107 in my test

**Comment by HenryLoenwind** [comment]
ok, thx. For the record: That's the version that still uses the old (read: extremely well tested for years) RF code.
