### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by Kalman11** [ZeroNoRyouki/BigReactors#202]
Hi!
I've downloaded Extreme Reactors and ZeroCore. ZeroCore works fine, but if I install any version of ExtremeReactors, the game just crashes.
Here's the crash log:
https://pastebin.com/1n9a42sJ
I'm also running a server, here's its crashlog:
https://pastebin.com/w9jaXSPc
I got a bunch of mods (I'm not using a modpack, I've installed them individually, total 78 mods, would be 80 with ExtremeReactors)

**Comment by ZeroNoRyouki** [comment]
You have the 1.7.10 BigReactors jar in there

**Comment by Kalman11** [comment]
Yes, I've downloaded BigReactors first, then realized it was only for 1.7.10, then I've downloaded Extreme Reactors. I think I've sent the log created after I've deleted it and restarted. But the point is it crashes with Extreme Reactors and without Big Reactors

**Comment by ZeroNoRyouki** [comment]
Nop, it's still in there:

[22:31:17] [Server thread/INFO] [FML]: FML has found a non-mod file BigReactors-0.4.3A.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.

**Comment by Kalman11** [comment]
I know, I'll send you a fresh log at the weekend if I'll have free time.

ZeroNoRyouki <notifications@github.com> ezt írta (időpont: 2019. márc. 22.,
Pén 9:51):
