### ISSUE TITLE
The game crashed whilst initializing game Error: java.lang.NoClassDefFoundError: cpw/mods/fml/common/IWorldGenerator

### ISSUE THREAD

**Issue by NyannoKonekko** [ZeroNoRyouki/BigReactors#203]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  EnderCorePlugin (EnderCore-1.12.2.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  HCASM (HammerCore-1.12.2-2.0.4.5.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 5/6/19 7:15 PM
Description: Initializing game

java.lang.NoClassDefFoundError: cpw/mods/fml/common/IWorldGenerator
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:539)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: cpw.mods.fml.common.IWorldGenerator
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 38 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:539)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 404404000 bytes (385 MB) / 1073741824 bytes (1024 MB) up to 10737418240 bytes (10240 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2836 97 mods loaded, 97 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                | Version                | Source                                                      | Signature                                |
	|:----- |:--------------------------------- |:---------------------- |:----------------------------------------------------------- |:---------------------------------------- |
	| LC    | minecraft                         | 1.12.2                 | minecraft.jar                                               | None                                     |
	| LC    | mcp                               | 9.42                   | minecraft.jar                                               | None                                     |
	| LC    | FML                               | 8.0.99.99              | forge-1.12.2-14.23.5.2836.jar                               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge                             | 14.23.5.2836           | forge-1.12.2-14.23.5.2836.jar                               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | openmodscore                      | 0.12.2                 | minecraft.jar                                               | None                                     |
	| LC    | infinitylib                       | 1.12.2-1.12.0          | infinitylib-1.12.0.jar                                      | None                                     |
	| LC    | agricraft                         | 2.12.0-1.12.0-a6       | AgriCraft-2.12.0-1.12.0-a6.jar                              | None                                     |
	| LC    | appliedenergistics2               | rv6-stable-4           | Applied-Energistics-2-Mod-1.12.2.jar                        | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LC    | crafttweaker                      | 4.1.16                 | CraftTweaker-1.12.2.jar                                     | None                                     |
	| LC    | armoreablemobs                    | 1.1.2                  | ArmoreableMobs-Mod-1.12.2.jar                               | None                                     |
	| LC    | baubles                           | 1.5.2                  | Baubles-Mod-1.12.2.jar                                      | None                                     |
	| LC    | artifacts                         | 1.12.2-1.0.2           | Artifacts-Mod-1.12.2.jar                                    | None                                     |
	| LC    | bno                               | 1.12.2-1.0.4.0         | Basic-Nether-Ores-Mod-1.12.2.jar                            | None                                     |
	| LC    | mantle                            | 1.12-1.3.3.39          | Mantle-1.12-1.3.3.39.jar                                    | None                                     |
	| LC    | endercore                         | 1.12.2-0.5.37          | EnderCore-1.12.2.jar                                        | None                                     |
	| LC    | jei                               | 4.15.0.269             | jei_1.12.2-4.15.0.269.jar                                   | None                                     |
	| LC    | enderio                           | 5.0.25                 | Ender-IO-Mod-1.12.2.jar                                     | None                                     |
	| LC    | enderiointegrationtic             | 5.0.25                 | Ender-IO-Mod-1.12.2.jar                                     | None                                     |
	| LC    | tconstruct                        | 1.12.2-2.12.0.115      | Tinkers-Construct-Mod-1.12.2.jar                            | None                                     |
	| LC    | bhc                               | 1.2.3                  | baubley-heart-canisters-1.12.2-1.2.3.jar                    | None                                     |
	| LC    | botania                           | r1.10-360              | Botania-Mod-1.12.2.jar                                      | None                                     |
	| LC    | codechickenlib                    | 3.2.2.353              | CodeChickenLib-1.12.2.jar                                   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | redstoneflux                      | 2.1.0                  | RedstoneFlux-1.12-2.1.0.6-universal.jar                     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | brandonscore                      | 2.4.10                 | BrandonsCore-1.12.2-2.4.10.198-universal.jar                | None                                     |
	| LC    | buildcraftlib                     | 7.99.14                | BuildCraft-Mod-1.12.2.jar                                   | None                                     |
	| LC    | buildcraftcore                    | 7.99.14                | BuildCraft-Mod-1.12.2.jar                                   | None                                     |
	| LC    | buildcraftbuilders                | 7.99.14                | BuildCraft-Mod-1.12.2.jar                                   | None                                     |
	| LC    | buildcraftenergy                  | 7.99.14                | BuildCraft-Mod-1.12.2.jar                                   | None                                     |
	| LC    | buildcraftfactory                 | 7.99.14                | BuildCraft-Mod-1.12.2.jar                                   | None                                     |
	| LC    | buildcraftrobotics                | 7.99.14                | BuildCraft-Mod-1.12.2.jar                                   | None                                     |
	| LC    | buildcraftsilicon                 | 7.99.14                | BuildCraft-Mod-1.12.2.jar                                   | None                                     |
	| LC    | buildcrafttransport               | 7.99.14                | BuildCraft-Mod-1.12.2.jar                                   | None                                     |
	| LC    | buildhelper                       | 1.0.4.1                | BuildHelper-Mod-1.12.2.jar                                  | None                                     |
	| LC    | chancecubes                       | 1.12.2-3.2.3.242       | ChanceCubes-1.12.2-3.2.3.242.jar                            | None                                     |
	| LC    | cofhcore                          | 4.6.2                  | CoFHCore-1.12.2-4.6.2.25-universal.jar                      | None                                     |
	| LC    | cofhworld                         | 1.3.0                  | CoFHWorld-1.12.2-1.3.0.6-universal.jar                      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | conarm                            | 1.2.3.2                | Constructs-Armory-Mod-1.12.2.jar                            | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LC    | ctgui                             | 1.0.0                  | CraftTweaker-1.12.2.jar                                     | None                                     |
	| LC    | crafttweakerjei                   | 2.0.2                  | CraftTweaker-1.12.2.jar                                     | None                                     |
	| LC    | dldungeonsjdg                     | 1.11.2                 | Doomlike-Dungeons-Mod-1.12.2.jar                            | None                                     |
	| LC    | draconicevolution                 | 2.3.21                 | Draconic-Evolution-1.12.2-2.3.21.342-universal.jar          | None                                     |
	| LC    | enderiobase                       | 5.0.25                 | Ender-IO-Mod-1.12.2.jar                                     | None                                     |
	| LC    | enderioconduits                   | 5.0.25                 | Ender-IO-Mod-1.12.2.jar                                     | None                                     |
	| LC    | enderioconduitsappliedenergistics | 5.0.25                 | Ender-IO-Mod-1.12.2.jar                                     | None                                     |
	| LC    | enderioconduitsopencomputers      | 5.0.25                 | Ender-IO-Mod-1.12.2.jar                                     | None                                     |
	| LC    | enderioconduitsrefinedstorage     | 5.0.25                 | Ender-IO-Mod-1.12.2.jar                                     | None                                     |
	| LC    | enderiointegrationforestry        | 5.0.25                 | Ender-IO-Mod-1.12.2.jar                                     | None                                     |
	| LC    | enderiointegrationticlate         | 5.0.25                 | Ender-IO-Mod-1.12.2.jar                                     | None                                     |
	| LC    | enderiomachines                   | 5.0.25                 | Ender-IO-Mod-1.12.2.jar                                     | None                                     |
	| LC    | enderiopowertools                 | 5.0.25                 | Ender-IO-Mod-1.12.2.jar                                     | None                                     |
	| LC    | forgelin                          | 1.8.2                  | Forgelin-1.8.2.jar                                          | None                                     |
	| LC    | exnihilocreatio                   | 1.12.2-0.4             | exnihilocreatio-1.12.2-0.4.jar                              | None                                     |
	| LC    | excompressum                      | 3.0.27                 | ExCompressum_1.12.2-3.0.27.jar                              | None                                     |
	| LC    | extrautils2                       | 1.0                    | Extra-Utilities-Mod-1.12.2.jar                              | None                                     |
	| LC    | zerocore                          | 1.12.2-0.1.2.8         | zerocore-1.12.2-0.1.2.8.jar                                 | None                                     |
	| L     | bigreactors                       | 1.12.2-0.4.5.66        | ExtremeReactors-1.12.2-0.4.5.66.jar                         | None                                     |
	| L     | hammercore                        | 2.0.4.5                | HammerCore-1.12.2-2.0.4.5.jar                               | None                                     |
	| L     | waila                             | 1.8.26                 | Hwyla-1.8.26-B41_1.12.2.jar                                 | None                                     |
	| L     | improvableskills                  | 3.6.2r                 | ImprovableSkills-1.12.2-3.6.2r.jar                          | None                                     |
	| L     | ic2                               | 2.8.100-ex112          | Industrial-Craft-2-Mod-Experimental-1.12.2.jar              | None                                     |
	| L     | mekanism                          | 1.12.2-1.1.2           | mekanica-1.12.2-1.1.2.jar                                   | None                                     |
	| L     | tesla                             | 1.0.63                 | Tesla-1.12.2-1.0.63.jar                                     | None                                     |
	| L     | teslacorelib                      | 1.0.15                 | tesla-core-lib-1.12.2-1.0.15.jar                            | None                                     |
	| L     | industrialforegoing               | 1.12.2-1.12.2          | Industrial-Foregoing-Mod-1.12.2.jar                         | None                                     |
	| L     | lootbags                          | 2.5.8.5                | LootBags-1.12.2-2.5.8.5.jar                                 | None                                     |
	| L     | mekanismgenerators                | 1.12.2-1.1.2           | Mekanica-Generators-Mod-1.12.2.jar                          | None                                     |
	| L     | mekanismtools                     | 1.12.2-1.1.2           | Mekanica-Tools-Mod-1.12.2.jar                               | None                                     |
	| L     | projecte                          | 1.12.2-PE1.4.0         | ProjectE-Mod-1.12.2.jar                                     | None                                     |
	| L     | moartinkers                       | 0.6.0                  | moartinkers-0.6.0.jar                                       | None                                     |
	| L     | openmods                          | 0.12.2                 | OpenModsLib-1.12.2-0.12.2.jar                               | None                                     |
	| L     | openblocks                        | 1.8.1                  | OpenBlocks-1.12.2-1.8.1.jar                                 | None                                     |
	| L     | harvestcraft                      | 1.12.2zb               | Pam's+HarvestCraft+1.12.2zc+The+7mm+Kidney+Stone+Update.jar | None                                     |
	| L     | plustic                           | 7.0.2.0                | PlusTiC-Mod-1.12.2.jar                                      | None                                     |
	| L     | projectintelligence               | 1.0.4                  | ProjectIntelligence-1.12.2-1.0.4.17-universal.jar           | None                                     |
	| L     | quantumflux                       | 2.0.18                 | quantumflux-1.12.2-2.0.18.jar                               | None                                     |
	| L     | redstonearsenal                   | 2.6.2                  | RedstoneArsenal-1.12.2-2.6.2.17-universal.jar               | None                                     |
	| L     | roughmobs                         | 1.0                    | roughMobs1.0.14-1.12.2.jar                                  | None                                     |
	| L     | ruins                             | 17.1                   | Ruins-Mod-1.12.2.jar                                        | None                                     |
	| L     | spartanshields                    | 1.5.2                  | SpartanShields-1.12.2-1.5.2.jar                             | None                                     |
	| L     | spartanweaponry                   | beta 1.2.3             | SpartanWeaponry-1.12.2-beta-1.2.3.jar                       | None                                     |
	| L     | shinygear                         | 1.5                    | Shiny-Gear-Mod-1.12.2.jar                                   | None                                     |
	| L     | simplyjetpacks                    | 2.2.11.64              | Simply-Jetpacks-2-Mod-1.12.2.jar                            | None                                     |
	| L     | taiga                             | 1.12.2-1.3.3           | TAIGA-Mod-1.12.2.jar                                        | None                                     |
	| L     | tinkertoolleveling                | 1.12-1.0.3.DEV.56fac4f | Tinkers-Tool-Leveling-Mod-1.12.2.jar                        | None                                     |
	| L     | tinkerscompendium                 | 1.4.2.23               | tinkersdefense-1.4.2.23.jar                                 | None                                     |
	| L     | torohealthmod                     | 1.12.2-11              | torohealth-1.12.2-11.jar                                    | None                                     |
	| L     | bspkrscore                        | at_0.9                 | TreeCapitator-Mod-1.12.jar                                  | None                                     |
	| L     | treecapitator                     | at_0.9                 | TreeCapitator-Mod-1.12.jar                                  | None                                     |
	| L     | uteamcore                         | 2.2.4.94               | U-Team-Core-1.12.2.jar                                      | None                                     |
	| L     | usefulbackpacks                   | 1.3.1.13               | Useful-Backpacks-Mod-1.12.2.jar                             | None                                     |
	| L     | vanilladeathchest                 | 1.12.2-1.9.0.0         | Vanilla-Death-Chest-Mod-1.12.2.jar                          | None                                     |
	| L     | veinminer                         | 0.38.1                 | Vein-Miner-Mod-1.12.jar                                     | None                                     |
	| L     | veinminermodsupport               | 0.38.1                 | Vein-Miner-Mod-1.12.jar                                     | None                                     |
	| L     | wawla                             | 2.5.269                | Wawla-1.12.2-2.5.269.jar                                    | None                                     |
	| L     | xaerominimap                      | 1.16.3                 | Xaeros-Minimap-Mod-1.12.jar                                 | None                                     |
	| L     | moofluids                         | 1.12.2-1.7.11.02a      | Moo-Fluids-Mod-1.12.2.jar                                   | None                                     |
	| L     | teslacorelib_registries           | 1.0.15                 | tesla-core-lib-1.12.2-1.0.15.jar                            | None                                     |

	Loaded coremods (and transformers): 
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  openmods.core.OpenModsClassTransformer
EnderCorePlugin (EnderCore-1.12.2.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
ForgelinPlugin (Forgelin-1.8.2.jar)
  
HCASM (HammerCore-1.12.2-2.0.4.5.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 398.11' Renderer: 'GeForce GTX 1060 3GB/PCIe/SSE2'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	AE2 Version: stable rv6-stable-4 for Forge 14.23.5.2768
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

	Launched Version: 1.12.2-forge1.12.2-14.23.5.2836

**Comment by ZeroNoRyouki** [comment]
Remove the jar for the 1.7.10 version of Big Reactors
