### ISSUE TITLE
1.12.2 Turbine Router Bearing issue...

### ISSUE THREAD

**Issue by Batosi001** [ZeroNoRyouki/BigReactors#205]
I noticed while walking on my turbine that you fall into the "Turbine Bearing" Block screenshot attached

![2019-06-04_19 17 49](https://user-images.githubusercontent.com/51070803/58919920-ec405e00-86fd-11e9-990f-8bda397f954f.png)
 
Don't think i should be standing in the Turbine Bearing lol

**Comment by ZeroNoRyouki** [comment]
You probably should not :)

Fixed in 0.4.5.67
