### ISSUE TITLE
Max output is 10mil rf/t.

### ISSUE THREAD

**Issue by mentimjojo** [ZeroNoRyouki/BigReactors#207]
Hi,

Is there a way to change the internal buffer of the reactor? Because it prevents the reactor from outputting more then 10 mil rf/tick. I would be awesome if their was a way to change it in the configs.

Thanks already for reading!

**Comment by ZeroNoRyouki** [comment]
Already answered here: https://minecraft.curseforge.com/projects/extreme-reactors?comment=316

Z

**Comment by Machine-Maker** [comment]
How does that comment answer that question? We have the same issue where 10 mil is the max regardless of what the reactor says its generating.
