### ISSUE TITLE
Sinc Problems on Servers + No ender Io Conduit support?

### ISSUE THREAD

**Issue by Medusalem** [ZeroNoRyouki/BigReactors#21]
Playing on our Server with extrem Reactors, one have to relog to see which fluids are in which fluid container, if you use a extream reactor to produce steam! I think it is a kind of Sic issue which is also seable in the transfer nodes from extra utilitys, which need a relog to show what they are piping in or out.

Also it is not able to put in fluids or take out steam via Ender Io conduits!

You can find a modlist of our server at https://mods.curse.com/modpacks/minecraft/250392-dionysos

I am sorry for my bad english!

**Comment by ZeroNoRyouki** [comment]
Hi there.

Please check issue #18 

Which version of Ender IO are you guys using?

**Comment by Medusalem** [comment]
Extra Utilitys is in version alpha 1.0.1
Ender io in version 3.0.1.112_beta

And it's not able to get fluids in or out! 
I can put steam in the turbine with ender io conduits but not out of the reactor!

I tested with reloging and piping directly in the Turbine and in tanks from ender io and Extra utilitys, to see if something finds its way in there with the conduits, but they do not.

Only way piping out for me was via Transfer nodes. And that was not going well eather because and export buss can pipe in water in the Steam tank of the Reactor, which is sstrange in my eyes!

**Comment by ZeroNoRyouki** [comment]
Are you still experiencing this issue?
thanks

**Comment by Medusalem** [comment]
Have to check, we changed World and because of fps drops near reactors on a version we had no for a long time, i will build one tomorrow and will shair my expierience

**Comment by ZeroNoRyouki** [comment]
I'm closing this. If you still have some problems please open another issue

Thank you
