### ISSUE TITLE
Reactor RedNet Port and Extreme reactors Mod

### ISSUE THREAD

**Issue by Babo357** [ZeroNoRyouki/BigReactors#218]
Hello
Since MineFactory mod is no longer aviable for MC 1.12.2.
Is there any other use  of the Reactor RedNet Port in Extreme Reactors mod, with other mods (wich one?), I have installed project red mod and bundle cable doesn't seems to work.
Thanks

**Comment by ZeroNoRyouki** [comment]
Currently the RedNet Port has no active use because it depend on the RedNet API which is not available on 1.12.2.
