### ISSUE TITLE
Turbine rotor rendering issues.

### ISSUE THREAD

**Issue by RogueLogic** [ZeroNoRyouki/BigReactors#22]
In some cases the turbine rotor can be rendered in an abnormal way. the following screen shots were taken of this behavior. Note, this was in a dev environment but a regular BR jar.
BR version 1.10.2-0.4.5.16
ZeroCore version 1.10.2-0.0.8.0
gpu:
GTX 980ti driver 372.90
![2016-10-02_22 38 51](https://cloud.githubusercontent.com/assets/9971693/19028517/c7de6730-88f1-11e6-9e34-dba823f29985.png)
![2016-10-02_22 38 58](https://cloud.githubusercontent.com/assets/9971693/19028518/c7ed8206-88f1-11e6-912e-e20181d193a4.png)
![2016-10-02_22 39 04](https://cloud.githubusercontent.com/assets/9971693/19028519/c7f71c80-88f1-11e6-9aff-6964859cbe36.png)

**Comment by RealGrep** [comment]
There's issues for sure, and I assume that part is a work in progress. I have about half the blades rotated incorrectly. They face completely wrong directions. Looks really weird! At least yours are oriented correctly. Thought it was worth mentioning, but didn't want to log a separate issue since I assume it's being worked upon, and already known. If you wish me to log a separate issue and post screenshots, though, let me know.

**Comment by ZeroNoRyouki** [comment]
Yes thank you, some screenshots could be helpful :)

**Comment by RogueLogic** [comment]
The blades also seem to only be rendered when the rotor bearing is whiten your FOV after initial assembly. ill ad screenshots later.

**Comment by ZeroNoRyouki** [comment]
Yes, that's correct (from Minecraft' POV anyway..)

**Comment by RogueLogic** [comment]
update:
ER version: 0.4.5.21
ZeroCore: Version 0.0.8.2
Again in Dev env (ZC from maven) but regular ER jar.

Nvidia GTX 980ti with driver 376.09
![2016-12-11_00 01 07 - copy](https://cloud.githubusercontent.com/assets/9971693/21083016/5dcdb026-bf9c-11e6-847d-a5ed3d228938.png)
![2016-12-11_00 03 36](https://cloud.githubusercontent.com/assets/9971693/21083013/5dccb2de-bf9c-11e6-965d-f51a6a5e120b.png)
![2016-12-11_00 01 38](https://cloud.githubusercontent.com/assets/9971693/21083015/5dcd62d8-bf9c-11e6-8123-3ad0bd2371e6.png)
![2016-12-11_00 01 13](https://cloud.githubusercontent.com/assets/9971693/21083017/5dcdec62-bf9c-11e6-8c89-7e999075890e.png)


AMD R9 Fury; Driver: Crimson 16.21.1 ReLive edition.
![2016-12-11_12 18 21](https://cloud.githubusercontent.com/assets/9971693/21083040/a773ffbe-bf9c-11e6-8f16-5041a666a099.png)
![2016-12-11_12 18 18](https://cloud.githubusercontent.com/assets/9971693/21083041/a7744aaa-bf9c-11e6-98fb-c4473f712be8.png)
![2016-12-11_12 18 35](https://cloud.githubusercontent.com/assets/9971693/21083042/a7750210-bf9c-11e6-9d13-2aa23c7178b0.png)

**Comment by trollworkout** [comment]
you got no texture bound to the turbine blades. it pretty much uses whatever is in the buffer and so it happens in Intel is always the same color. you not doing properly you need to do it using vanilla addBox and create a model so you get proper lighting and texturing

**Comment by ZeroNoRyouki** [comment]
Yes, I'm using a open gl display list to render the rotor and speeds things up

I was under the impression that BlockRendererDispatcher was already binding the block textures atlas. Let's me check it and see if it was something soo stupid

**Comment by ZeroNoRyouki** [comment]
It's not handling it after all. Thanks for the help

Fixed in the next release

**Comment by RogueLogic** [comment]
thank god.
