### ISSUE TITLE
Turbine computer port, add getVentMode function

### ISSUE THREAD

**Issue by arduinka55055** [ZeroNoRyouki/BigReactors#221]
i am creating turbine(and reactor, 2 in 1) control software, and i want to get current vent state if user occasionally will toggle it outside my program.
it is useful, and not hard to implement in java code

**Comment by Tahakk** [comment]
The reactor already provides lot of information, there are programs that controls reactors/turbines on these informations. You can look at the [BRGC](https://tenyx.de/brgc/) that controls all the different things using reactor info and see how is he getting the information.

**Comment by ZeroNoRyouki** [comment]
@arduinka55055 : added to the TODO list

**Comment by arduinka55055** [comment]
thanks, i am waiting for next updates. this mod is useful with permanent shortage of energy :)

and thanks for BRGC, but i want to make app for MineOS 
https://github.com/IgorTimofeev/MineOS/

**Comment by Tahakk** [comment]
The MineOS is using Lua same as OC, so you can just figure out how they do it. I wasn't suggesting for you to use the whole program :) 
Maybe you want to do something completely else and I just don't get it :)
All I can remember is that Zero was working with the BRGC guy in past to make all kinds of improvements
