### ISSUE TITLE
Any chance of a 1.15 update?

### ISSUE THREAD

**Issue by miiichael** [ZeroNoRyouki/BigReactors#222]
I would love for there to be an ER for 1.15 when I get around to updating my modpack/server to 1.15. :sweat_smile:

Any chance of this happening?

**Comment by ZeroNoRyouki** [comment]
https://www.curseforge.com/minecraft/mc-mods/extreme-reactors#c501

**Comment by scollenburg** [comment]
Thanks for the update ZeroNoRyouki . FWIW, cpw popped into chat a few days ago & essentially encouraged folks (modders & pack makers) lean into 1.15. cpw said vanilla 1.16 had major changes so it will be a few months before its ready for prime time.

**Comment by ZeroNoRyouki** [comment]
@scollenburg thank you for sharing that
