### ISSUE TITLE
Er/ de conflict

### ISSUE THREAD

**Issue by Stevekratz** [ZeroNoRyouki/BigReactors#23]
I'm kind of new to this so forgive me if I'm not doing this right.  I'm playing the all the mods pack with optifine, woot and ender utilities added to it (as of 10/3/2016 all mods are up to date with the newest releases).  The issue I'm having is when I try to use an extreme reactor in combination with the draconic evolution power storage.  Reactors will work fine until I activate the draconic storage system.  After it has been activated the reactors (all of them in the world) stop outputting power.  They still fire up and use fuel and report that they are generating RF but their buffers never get power and no power comes out of the reactor taps.  Breaking and replacing doesn't seem to help nor reloading the game

**Comment by ZeroNoRyouki** [comment]
Could you please tell me the version numbers of Forge, DE, ER ?

Also, could you post a pic of your setup somewhere?

thank you

**Comment by Morpheus1101** [comment]
Have you tried connecting the Reactor to a DE Pylon via a cable and seeing if the particles are flowing form the pylon to the core?

**Comment by Stevekratz** [comment]
I think this has been fixed.  This morning I saw there were some updates on the modpack for DE as well as a few other mods so I installed them and it seems to have fixed the issue.
