### ISSUE TITLE
[1.10.2-0.4.5.17] Turbine blades incorrectly oriented visually

### ISSUE THREAD

**Issue by RealGrep** [ZeroNoRyouki/BigReactors#25]
Some of the blades on my turbine are oriented incorrectly. This is visual, and it functions just fine, but just looks really weird. As requested, logging this separate issue and providing you with some screenshots of it.

![2016-10-06_19 41 39](https://cloud.githubusercontent.com/assets/1060816/19174562/9c21556c-8bfd-11e6-8503-55b6af6c9484.png)
![2016-10-06_19 41 50](https://cloud.githubusercontent.com/assets/1060816/19174561/9c210fd0-8bfd-11e6-83aa-e7d6fd005ba9.png)
![2016-10-06_19 42 04](https://cloud.githubusercontent.com/assets/1060816/19174563/9c25aff4-8bfd-11e6-8082-dead16fd507e.png)

Other than this visual glitch, working quite nicely, so thanks a lot for the port! Just got Direwolf20's reactor control program working roughly on OpenComputers.

**Comment by ZeroNoRyouki** [comment]
Thank you

Quick question: do you use Optifine? If so, could you test it again without it?

Thanks

**Comment by RealGrep** [comment]
Nope, no optifine.

**Comment by RogueLogic** [comment]
could you give specifics on the turbine this happened with? ie n, s, e w. i tried to replicate this without success.

**Comment by RealGrep** [comment]
Sure thing. It's directly connected to the reactor. It's oriented so the long side runs north-south, and has the dimensions of 9x9x16 (outside). The coolant valves are south, along with the coils (which are now ludicrite, but were gold). The shaft runs the 14 blocks inside, with the bearing on the north side. It has 80 blades. The north blades against the bearing are three long each, for 12 blade blocks per shaft segment, except for the last southern set of blades, which are each 2 long, for 8 blades on the last southern set. That leaves three rotor shaft segments with no blades, before hitting the 32 ludicrite blocks. They extend all the way to the south face, and so are 4 blocks in length (8 blocks per rotor shaft segment, of course).

Top and bottom are all casing, but all four n/s/e/w sides are turbine glass, except for the required blocks like the controller, power tap, rotor bearing (north), and the turbine casing against the south side of the rotor shaft, which is the side where the reactor and coolant ports are.

This might be handy in re-creating it. This is the .schematic file I saved with Schematica. It still had the gold blocks, but not important. Might even work to MCEdit it in. Never tried with Schematica schematics. It includes the reactor, as well.

[BRTurbineSetup1.schematic.zip](https://github.com/ZeroNoRyouki/BigReactors/files/517753/BRTurbineSetup1.schematic.zip)

**Comment by RogueLogic** [comment]
that replicated it. the issue only appears when a turbine is built horizontally n/s. a e/w turbine the blades are fine. it also only affects the up and east blades

**Comment by RealGrep** [comment]
Awesome, thanks for looking into it! :D

**Comment by RogueLogic** [comment]
ZeroNoRyouki/BigReactors#26 fixes this issue

**Comment by KamranMackey** [comment]
I have reused your fix and merged it to my repository, but I had to do it manually, as I don't know how to merge PRs to a different repo using Git on Windows.
