### ISSUE TITLE
Turbine steam not working with EnderFluid Conduit

### ISSUE THREAD

**Issue by MCTyler** [ZeroNoRyouki/BigReactors#31]
I set up 4 cooling vents, and 4 Turbine steam intake vents and the highest rotor speed I can obtain is 800 RPM. I even tried to configure EnderIO.cfg with crazy OP numbers in the settings with still no avail. Is there something I'm missing? 

Forge 2099, EnderIO 107.Beta, and EXtReac 5.17

**Comment by ZeroNoRyouki** [comment]
How many blades you have in the turbine?

Can you post a pic of your setup somewhere?

**Comment by MCTyler** [comment]
I finally figured it out. The ExtraUtils2 Retrieval node wasn't pulling enough water so I had to go super OP with those, I think it took 12 nodes and 12 coolant ports ;)....There is no config option for those retrieval nodes dang it.

**Comment by MCTyler** [comment]
Let me try here.....
[[Imgur](http://i.imgur.com/Mf8Ctmj.png)](url)

**Comment by RogueLogic** [comment]
You still have a few problems. A) you aren't recycling the water. B) you left a block I between the turbine and reactor. C) stack upgrades. D) a stack of world interaction upgrades. All just your setup though.

**Comment by MCTyler** [comment]
There is no World Intergration in the setup for ExtraUtils2. I'll try stacks real quick...(Nope, that doesn't change the retrieval Node) Thanks though, none of this has to do with your mod.

**Comment by ZeroNoRyouki** [comment]
ok, good

Z
