### ISSUE TITLE
StackOverflowError at startup

### ISSUE THREAD

**Issue by MakerTim** [ZeroNoRyouki/BigReactors#32]
I got a StackOverflowError when server is starting up, could be a crash before rebooting, but nog logs of that :/

http://pastebin.com/uiM7ZRmH

The change that happend was the output block that is outputting to a enderchest (of chickenbones)
the normal chest seem to behave normal, but the enderchest is crashing

Forge 1.10.2 - 2094
ExtremeReactors-1.10.2-0.4.5.17

**Comment by ZeroNoRyouki** [comment]
Fixed in 1.10.2-0.4.5.18
