### ISSUE TITLE
FPS Drop

### ISSUE THREAD

**Issue by Medusalem** [ZeroNoRyouki/BigReactors#33]
System Information

So, We play the verstion 0.4.5.17, included in the Modpack Dyonisos https://minecraft.curseforge.com/projects/dionysos.

Because of the Other thread, the Extrem Reactor is conected with ender io Item and energy Conduits, but no other Mods are conected to the Powersystem!

Forge Version is 12.18.2.2017

The Problem:
Looking at a Big reactor leads to a Massive FPS Drop!

depending of the sice of the reactor,/( We tested from Smal to Maximum size, the Reactor is causing huge fps drops if player is looking in the direction of a reactor!

Reaktors without windows have the same impackt than Reactors without, and even beeing around 30 -60 blocks away, and looking in the direction of the reactor can drop the Fps down to 80 if near a normal size reactor and down to 20 if near a maximum sized reactor, standing directly to it will drop fps down to arround 4-15 Fps.

There was always a bit of Fps drop with big reactors in BIG sizes in 1.70.10 but this is kind of extrem!

**Comment by RogueLogic** [comment]
Do consider that BR 1.7.10 and ER 1.10.2 have completely different renderers. There was a massive update to Forge from 1.7 -> 1.8+ and the rendering code had to be rebuilt. This means it is buggy and does not have the performance testing that the 1.7.10 engine did so this drop is to be expected.

As for my personal experiences I have had no problem keeping frame rates high on my computer, as seen in screenshot. Your computers specs and a baseline FPS is necessary to attempt to remedy this problem.

FYI, you have a typo in your forge version forge version 12.18.2.2017 does not exist. Version 12.18.2.2107 and 12.18.1.2017 do however. Can you confirm the forge version.

![2016-10-21_01 37 20](https://cloud.githubusercontent.com/assets/9971693/19592142/42c69012-972f-11e6-8c1f-a0cf73872fd7.png)

**Comment by Medusalem** [comment]
Forge version is: 12.18.2.2107 , made a typo, my bad, for testing i would say fill the Reactor up with Fuelrods, Because bigger reactors with Bigger Fuel Rods tent to make a bigger fps drop!

If i unleash the Framerate and do not look at a reactor framerate goes up to 240, and is moving between 160 and 200 Fps, looking at a small reaktor, full of fuel rods, cooled by a bit of diamond blocks, framerate goes down to 80 Frames per Second.

A max sized reaktor filled with fuelrods and A diagonal line of Diamond blocks drops the fps down to 8!
Interesting is, that a huge ammounds of Fuelrods, without fuel or a complete reactor does fps droping as well as we found out while building it, but in a Multiblock raktor, so as it if it is finished fps goes down to 8, from 60-80 standing near to it and not looking at it and 3-12 if looking at it direktly, having a wall and a few block between it helps, but it is not like it is not there!

**Comment by Medusalem** [comment]
Pc specs, cause i was not at home now:

I5, 6500

16gb ram, 8 gigs alocaded 

nividia Gforce gtx 960

Minecraft running on an ssd

**Comment by ZeroNoRyouki** [comment]
Solved in the next release. Reactors without glass are much FTP friendly now

![2016-10-21_14 06 34](https://cloud.githubusercontent.com/assets/7107662/19597979/3f028a8a-9798-11e6-9d1a-cb973f6fad9d.png)

**Comment by Medusalem** [comment]
Nice to hear that, wenn will it be life and just out of curiosity, what was the Problem or cause of the fps drops?

**Comment by ZeroNoRyouki** [comment]
In the weekend probably. Fuel rods rendering

**Comment by ZeroNoRyouki** [comment]
1.10.2-0.4.5.18 is out
