### ISSUE TITLE
Can't set control rod label

### ISSUE THREAD

**Issue by OrdinatorStouff** [ZeroNoRyouki/BigReactors#34]
I am unable to "save" control rod names in the UI. I type a name in, press the save button but when I exit and re-enter the control-rod UI, it has no name displayed again.

This was discovered today while playing with Extreme Reactors version 1.10.2-0.4.5.17 in a highly customized Unstable 1.10 instance with Forge 12.18.2.2098 and many mods added and existing ones updated. I have not been able to test this with only Extreme Reactors installed by its self. I can provide an entire mod list if necessary/relevant (i.e. if suspected conflict).

**Comment by ZeroNoRyouki** [comment]
Fixed

The fix will be included in the next release

**Comment by ZeroNoRyouki** [comment]
1.10.2-0.4.5.18 is out

**Comment by ZeroNoRyouki** [comment]
Fixed. Thanks for the report

**Comment by OrdinatorStouff** [comment]
Thank **you** for active development/fork/bugfixing~!
