### ISSUE TITLE
Control rods not on the top decrease reactivity to 100%

### ISSUE THREAD

**Issue by kzkv** [ZeroNoRyouki/BigReactors#37]
I'm not sure if that's intended, but I tried a reactor setup wit control rods on the bottom and on the side, the result if 100% reactivity with the following dramatic fuel consumption increase.

Control rods on the top work fine (but still the numbers are closer to the direwolf20 build than a classic Big Reactors — is that correct?)

Thank you for you work, It's amazing to have my favourite power solution in 1.10 pack!

**Comment by RogueLogic** [comment]
what version are/were you playing with?

**Comment by ZeroNoRyouki** [comment]
No, it's not intended. I'll check it.

Thanks for the report

**Comment by kzkv** [comment]
Guys, I'm using Hermitpack 1.1, to I have Extreme Reactors 0.4.5.17.

Cheers!

**Comment by ZeroNoRyouki** [comment]
Fixed in the next release

Cheers
