### ISSUE TITLE
Coolant Registry API.

### ISSUE THREAD

**Issue by RogueLogic** [ZeroNoRyouki/BigReactors#39]
I would like to be able to pull the reactor coolants and balancing from ER. Simple enough.
This is primarily for the Exotic Coolant update so that other multiblocks, such as my Fusion reactor, are guaranteed to work with the same fluids.

**Comment by ZeroNoRyouki** [comment]
You can already get the data of the reactants you are interested in, namely the ones your players put in your reactor.

**Comment by RogueLogic** [comment]
*I don't think you got what I meant*
