### ISSUE TITLE
Crash when breaking Filled fuel rod

### ISSUE THREAD

**Issue by KristjanKr** [ZeroNoRyouki/BigReactors#4]
Forge: 2075
Extreme Reactors:ExtremeReactors-1.9.4-0.4.5.7.jar
Zerocore:zerocore-1.10.2-0.0.8.0.jar

What you expected to happen:
not crash

what happend:
Game crashed when dissasembling "extreme reactor" and breaking the filled fuel rod caused the game to totally crash..

Crash log: https://paste.ee/p/2vpQI

**Comment by ZeroNoRyouki** [comment]
Thank you for the report

I found where a possible problem is but I can't still reproduce the crash. How are you breaking the fuel rod?

Thank you
Z

**Comment by KristjanKr** [comment]
Imagine three tall fuel rod (controller to ground) .. I broke the middle.

**Comment by ZeroNoRyouki** [comment]
Did you use a vanilla pick? Some other tool?

**Comment by KristjanKr** [comment]
I used my hand.

**Comment by KristjanKr** [comment]
public int getFueldRodsCount() {
        return this._fuelRods.length;
    }

    public FuelRodData getFuelRodData(int rodIndex) {
        return this._fuelRods[rodIndex];
    }

This is the current code that is responsible for crashing.. As I broke 3 tall fuel rod in the middle.. then it obviously fails to get FuelRodData as the fuel rod is no longer valid. Maybe add check to fix it? Im not java developer but this is just an idea, when looking around at the code.

**Comment by ZeroNoRyouki** [comment]
Yes, the crash is there and I've already added a check. But it should not happening anyway and I can't still reproduce it

Gotta push the changed file anyway

**Comment by KristjanKr** [comment]
Well then I will check if it fixes it or not :)

**Comment by KristjanKr** [comment]
And maybe report here?

**Comment by ZeroNoRyouki** [comment]
Fixed in 0.4.5.8
