### ISSUE TITLE
Config options.

### ISSUE THREAD

**Issue by RogueLogic** [ZeroNoRyouki/BigReactors#40]
Additional config options that would be nice to see IMO.

-= Turbine options =-
- Max turbine steam. Self explanatory.
- Max coil distance from rotor. allow for multilayered coils increasing turbine density. Would require a partial rewrite of the turbine assembler.
  -  loss per block away. create loss by the coil being further from the rotor. only applicable with above option as well.
- default turbine values. This would include default steam per tick, fluid response, active, and coil active.
- Require two bearings. OCD, should also help with the rotor FOV issue.
- Allow Multiple Rotors. Simple idea, insane to add in.

-= Reactor options =-
- Max reactor steam. the 50B/t limit is a pain, pure and simple.
- Allow horizontal rods. Vertical rods are, to and extent, more realistic than horizontal.
- Can produce power. Not allow a reactor to produce RF or T directly but require a turbine. IK this can be done by setting the power multiplier to 0 but this option should also remove the power taps.
- Radiation distance. currently radiation travels a max of four blocks. i want to change that.

**Comment by scalda** [comment]
The dimension whitelist doesn't stick to what it is set to when the mod is loaded.

**Comment by RogueLogic** [comment]
first, that has nothing do do with this thread. second, you did save the file, correct?

**Comment by scalda** [comment]
added a new issue

**Comment by RogueLogic** [comment]
any news on any of these?

**Comment by cloakable** [comment]
It would also be nice to see the old steel instead of iron recipe back in; it's quite possible to make steel in 1.10.2 now.

**Comment by RogueLogic** [comment]
the old (1.6.4-1.7.10) recipes were iron not steel.

**Comment by Hypsellis** [comment]
I suggest here what I had suggested on Curse, add an option for preventing that the Uranium overrides all the Yellorium recipes, get Yellorium ingot and dust even when Uranium is present too.

**Comment by Rixxaw** [comment]
Steel Recipes were from Expert mode.

**Comment by Killerhurtz** [comment]
I disagree about removing power taps personally on the grounds that removing options for the sake of removing options is a terrible idea. Instead, I would advocate adding in a radiothermal element - a block that, when placed in a column, allows drawing power directly.

**Comment by RogueLogic** [comment]
This is for config additions, not default.
