### ISSUE TITLE
Crafting Handler error with IC2

### ISSUE THREAD

**Issue by abused** [ZeroNoRyouki/BigReactors#42]
Hello,
So i was working on my mod today called Super Ores, trying to add support for the ores in Extreme Reactors, but am having a really annoying if i do say so, conflict with ic2 whenever i attempt to register the crafting recipes for all 3 of the ores. http://pastebin.com/yDvuP5n0 that is currently my craftinghandler class, all of the recipes load fine except yours. I have run into this problem before with mekanism's osmium but thats a different story. The crash report is always the same, http://pastebin.com/q66DRt2H

**Comment by ZeroNoRyouki** [comment]
If I have to take a guess, your ModBlocks.YelloriteOre is NULL

Z

**Comment by abused** [comment]
it isnt just Yellorite its all 3 ores from the mod, and im registering them the exact same way i am to other ores, and they work just fine

**Comment by RogueLogic** [comment]
This is not the correct place to ask this, the [MMD Discord](https://discord.gg/PQPUT) would be far better.

**Comment by ZeroNoRyouki** [comment]
If they are NULL than you are probably getting my ores in the wrong way and/or at the wrong time

**Comment by RogueLogic** [comment]
I've had no problem getting ludicrite and the other blocks.

**Comment by ZeroNoRyouki** [comment]
@abused : judging from a cursory look at the code you have available right now on Curse, you are getting the ore early. It look like that you have noting in place to guarantee the all those ores (not only my own) actually exist when your code run

@RogueLogic : I'm sorry to have to say so, but it's not your place to say what or what not is correct here :(

**Comment by abused** [comment]
@ZeroNoRyouki the code on github is outdated and for 1.8.9, from then i have completely changed how i am registering recipes and blocks, etc. it has also come to my attention that i may have the oreDictionary names for Yellorite, Anglesite, and Benitoite

**Comment by ZeroNoRyouki** [comment]
@abused I known, that's why I checked the JAR from Curse and not the code on GitHub.
I did not get the bit about the ore dict

**Comment by ZeroNoRyouki** [comment]
If that bit about the ore dictionary was a question, the ore dict name for Yellorite is oreYellorite. Benitoite and Anglesite Ore do not have a ore dict entry.

**Comment by abused** [comment]
Aha, did not know that, i had the Yellorite but the Benitoite and Anglesite weere the problems for a null output. Now for the question, do you plan on registering the oreDict names for them?

**Comment by ZeroNoRyouki** [comment]
Nop

**Comment by ZeroNoRyouki** [comment]
And you still can get NULL for Yellorite, because your code could run before mine

**Comment by abused** [comment]
Lol all right then, just gonna remove em if thats the case, thx anyways

**Comment by abused** [comment]
And ill have to see what imma do about my code running first i could just do a chrck to see if the oreDictionary name exists first

**Comment by ZeroNoRyouki** [comment]
Just add the other mods as a non-required dependency and FML will sort that out for you

**Comment by abused** [comment]
That could also work, thx
