### ISSUE TITLE
Particle effects missing and yellorium not showing

### ISSUE THREAD

**Issue by SlackerNet** [ZeroNoRyouki/BigReactors#43]
Using minecraft 1.10.2
forge 12.18.2.2120
extreme reactors 0.4.5.18
pack = all the mods

The yellorium doesn't show when the reactor is filled and no particle effects either. The reactor still works just fine using rf power

image link

https://imgur.com/a/qiiOu

**Comment by ZeroNoRyouki** [comment]
Yup I'm aware of that :(

It's already fixed in the upcoming next release
