### ISSUE TITLE
In-Game Update Notification

### ISSUE THREAD

**Issue by Darkosto** [ZeroNoRyouki/BigReactors#44]
Please allow for an option to disable the update notification in-game. This message also appears when I already have the latest version installed.

Thanks, 
Darkosto

**Comment by ZeroNoRyouki** [comment]
uhm that should not happen. Are you getting the notification for both ER and ZeroCORE or only ER?

**Comment by ZeroNoRyouki** [comment]
I figured it out.. you should not get it anymore for the current version.

damn gradle...
