### ISSUE TITLE
dimension whitelist not saving

### ISSUE THREAD

**Issue by scalda** [ZeroNoRyouki/BigReactors#45]
dimension whitelist is not loading on a reload of the pack (hermitpack) i am trying to add the dimensions from ExU2, (deep dark, quarry) i have saved it, all other settings are fine and don't get replaced that i have changed. (latest version of the mod)

**Comment by ZeroNoRyouki** [comment]
could you please post your config file on [pastebin ](http://pastebin.com/)?

thank you

**Comment by scalda** [comment]
Sorry for being late i never got notified you had replied

Here is the config [link](http://pastebin.com/U3q0p0gw)

**Comment by Drock1994** [comment]
I had the same problem when adding Armoa1997 mining wolrd which is dim 6.

http://pastebin.com/sfVVHxds

**Comment by ZeroNoRyouki** [comment]
The problem is the commas, remove them. This is valid for any mods btw
