### ISSUE TITLE
Breaking a Reactor Access Port block erases its inventory

### ISSUE THREAD

**Issue by just-a-bird** [ZeroNoRyouki/BigReactors#47]
Any contained fuel or waste is deleted when the block is broken.

- [**WyldLife** 1.2.2](https://minecraft.curseforge.com/projects/wyldlife/files/2340937)
- **Minecraft** 1.10.2
- **Forge** 12.18.2.2116
- **Extreme Reactors** 0.4.5.18

**Comment by ZeroNoRyouki** [comment]
Thank you for the report.

Fixed in the next release
