### ISSUE TITLE
Water can be inserted into the hot fluid tank on the reactor!?

### ISSUE THREAD

**Issue by Glendening** [ZeroNoRyouki/BigReactors#48]
![2016-11-16_20 38 23](https://cloud.githubusercontent.com/assets/18632107/20372922/b0e0d64e-ac3c-11e6-82da-d1ebae354a3d.png)
As the screen shot shows. Somehow I pumped water INTO the hot side which shouldn't be possible and now I have no idea how to remove it or to reset the reactor =\
So how do I undo this and how do we prevent something other then steam from going in there?

Version ExtremeReactors-1.10.2-0.4.5.19.jar
Mod pack: All the mods
Used Ender IO ender fluid conduit to move fluids.

**Comment by RogueLogic** [comment]
Rebuilding the reactor as non-active may reset the tanks. If not you have to tear the reactor down if you can't pull it out normally.

**Comment by Glendening** [comment]
Rebuilding the reactor as non-active did not reset the hot tank. It did clear the water from the coolant tank however.
I ended up having to completely tear it down and rebuild it. Thinking back I should have grabbed the world file >.< for testing.

**Comment by ZeroNoRyouki** [comment]
Yeah, that could have been helpful :)

How did you put water in there in the first place? Just with pipes?

**Comment by Glendening** [comment]
Yep. Ender fluid conduit from ender IO. I'll make a small reactor to see if I can re break it for you.

**Comment by ZeroNoRyouki** [comment]
Thank you, I was able to reproduce it. I'll fix this in the next release

**Comment by ZeroNoRyouki** [comment]
Fixed
