### ISSUE TITLE
[1.10.2] Retro World Generation not Working

### ISSUE THREAD

**Issue by SnowShock35** [ZeroNoRyouki/BigReactors#49]
Hello,

I believe I have found a bug with Extreme Reactors for Minecraft 1.10.2.

### Important Information

- Minecraft 1.10.2
- Forge 12.18.2.2166
- Extreme Reactors 0.4.5.19
- ZeroCore 1.10.2-0.0.8.1

### Issue Description

So from what I can gather, the retro generation config option for Extreme Reactors doesn't work whatsoever. I've extensively tested this option in an attempt to make ores appear in previously generated chunks but yet to have any luck with it. I was able to use cpw's Simpleretrogen mod though to call your world generator to retro gen the ores. Just thought I'd mention that just to see if it helps.

**Comment by ZeroNoRyouki** [comment]
how do you test it?

**Comment by SnowShock35** [comment]
Create a world without extreme reactors, explore a little, then add it with retro gen in the config enabled and check to see if the already explored chunks have yellorium in and if yes then retro gen worked and if no then it did not and in my case it did not

**Comment by ZeroNoRyouki** [comment]
and did you mine all the old chunk blocks?

**Comment by SnowShock35** [comment]
yea I did a quarry over like 4 chunks. Also, when I added simple retro gen by cpw the retro gen was working so it was very clear that the retro generation wasn't working

**Comment by ZeroNoRyouki** [comment]
I did a quick test in my dev env with forge 2099 and the retrogen worked (starting from a world created in vanilla+forge only). I'll check if something changed in newer forge versions.

Can you give the me a list of the mods active during your test? thanks

**Comment by SnowShock35** [comment]
It's the Direwolf20 pack (version 1.1.0) for MC 1.10.2

**Comment by ZeroNoRyouki** [comment]
OK, I figured it out.

Retrogen per se worked just fine. In some circumstances the ores could "drift" in nearby chunks so you could end up with chunks with no ores in them.

Fixed in ER 1.10.2-0.4.5.20 / ZeroCORE 1.10.2-0.0.8.2

I've also tested in the in the last version of the DW20 pack by first creating a world and then adding ER in. Found 6 yellorite ores in my spawn chunk :)

**Comment by SnowShock35** [comment]
Thanks for the fix and for looking into this for me @ZeroNoRyouki. Much appreciated 😄

**Comment by ZeroNoRyouki** [comment]
You are welcome

Z
