### ISSUE TITLE
[1.10.2] [Feature Request] World Generation Blacklist 

### ISSUE THREAD

**Issue by SnowShock35** [ZeroNoRyouki/BigReactors#50]
Hello,

I have a small request for the extreme reactors configuration file.

The idea would be to have an option, similar to the current whitelist for world generation, however, for a blacklist instead. 

I say this because, if a modpack for instances has a dimension creating mod in it e.g. RFTools Dimensions, it would be really difficult to actually get ores in new dimensions created by that as they'd have different dimension id's. 

Obviously, it's entirely up to you whether you add such a feature, but, it would really help in this case because as it stands I will just have to make a huge whitelist in the hope that no players make more dimensions than id's I put in. 

Thanks. :)

**Comment by ZeroNoRyouki** [comment]
I'm already working on someting like that, basically an option to turn the world gen whitelist in a blacklist

**Comment by SnowShock35** [comment]
Nioce!
