### ISSUE TITLE
Rendering crash when placing rotor bearing in DW20 1.10 (v 1.1.2)

### ISSUE THREAD

**Issue by Chalmes** [ZeroNoRyouki/BigReactors#52]
Modpack is using the latest available Extreme Reactors (ExtremeReactors-1.10.2-0.4.5.20.jar)

Created a new world, cheated in a rotor bearing, placed in world and immediate client crash.

This happens both on this machine with the ATI Radeon, and also on an Nvidia 950M

Only occurs when LOOKING at the block.  If another player joins looking away, they are fine.  As soon as they rotate view with block in view (can be behind other blocks though) the crash will occur.

[crash-2016-12-06_10.17.59-client.txt](https://github.com/ZeroNoRyouki/BigReactors/files/632336/crash-2016-12-06_10.17.59-client.txt)

**Comment by Chalmes** [comment]
Note:  This worked fine in the previous version ExtremeReactors-1.10.2-0.4.5.19.jar.

**Comment by ZeroNoRyouki** [comment]
Thank you for the report.

Fixed in next release
