### ISSUE TITLE
Crash when placing Turbine Rotor Bearing

### ISSUE THREAD

**Issue by Aquahatsche** [ZeroNoRyouki/BigReactors#53]
I use the version 1.10.2-0.4.5.20 and everytime I try to place the Turbine Rotor Bearing my client crashes.
[crash-2016-12-08_05.14.13-client.txt](https://github.com/ZeroNoRyouki/BigReactors/files/638406/crash-2016-12-08_05.14.13-client.txt)

**Comment by ZeroNoRyouki** [comment]
Thank you for the report but please check other issues before posting a new one (#52)

The fix will be released today

Z

**Comment by Aquahatsche** [comment]
I didn't see the issue because it was closed. Obviously I read the opened one. Consider to label work in progress issues and close them after it has been fixed.

**Comment by RogueLogic** [comment]
There are many issues with Zero's processes as whole.
*nudge to actually update the github repos for both ER and ZeroCore*
