### ISSUE TITLE
Steam Turbines formed block textures are inverted on the east and south sides

### ISSUE THREAD

**Issue by Xiaminou** [ZeroNoRyouki/BigReactors#54]
Or they're inverted on the North and West side, not sure which way they're supposed to be, but the contour doesn't match.

![2016-12-09_15 14 19](https://cloud.githubusercontent.com/assets/8670392/21051894/907cec4c-be22-11e6-8a1f-9639a016dc72.png)
![2016-12-09_15 14 23](https://cloud.githubusercontent.com/assets/8670392/21051895/90905188-be22-11e6-8200-ba27097db8f7.png)

**Comment by ZeroNoRyouki** [comment]
We known since the beginning but we decided to leave it as that since the legacy blocks will not be around much longer

**Comment by Xiaminou** [comment]
Interesting, well I'm looking forward to those new blocks then.
