### ISSUE TITLE
Turbine Rotor Bearing appears to be causing a client-side crash.

### ISSUE THREAD

**Issue by AnonymousPepper** [ZeroNoRyouki/BigReactors#56]
http://pastebin.com/zSdsuSJu

The issue does not appear to take place in isolation, i.e. a completely vanilla+Extreme Reactors client, but the crash nonetheless occurs in all cases in All the Mods v1.50 where the block is placed, regardless of world state. A crash identical to the one in the above crashlog occurs on a superflat world with nothing else placed as soon as the Turbine Rotor Bearing is placed under any conditions. 

In the case of the multiplayer server I was on at the time, the server continues functioning, as it's just a rendering issue, but as I am right next to the block, I'm unable to relog without crashing as soon as the game world attemps to render.

I'm aware it's more than likely a pack issue, but I thought it should be brought to your attention anyway.

**Comment by RogueLogic** [comment]
please check the change log and for newer versions. https://minecraft.curseforge.com/projects/extreme-reactors/files
![changelog](https://cloud.githubusercontent.com/assets/9971693/21078866/07003a4c-bf34-11e6-9d42-5f53c119ba20.png)

**Comment by ZeroNoRyouki** [comment]
See #52 

Please update.
