### ISSUE TITLE
Turbine not producing RF with powertap installed

### ISSUE THREAD

**Issue by Everdyin1** [ZeroNoRyouki/BigReactors#57]
Running into a problem with the Turbines playing on Hermitpack 1.5.1 with both ExtremeReactors and ZeroCore manually updated to the newest version available.

 

My reactor and turbines work perfectly fine until I add a RF power tap to the turbines, yes i used the turbine one. At that point the turbine GUI shows that the turbine is producing X amount of RF/t but the energy buffer does not fill up.  Replacing the power tap with casing allows the turbine to run and fills the buffer quickly, but now i have no power tap to send it elsewhere, I tried the Tesla power tap just for kicks and the buffer filled with Tesla power just fine. I tried attaching both Mekanism and EnderIO cables to see if this was just a GUI bug and no power was output from the turbines.

![2016-12-17_05 30 38](https://cloud.githubusercontent.com/assets/24620601/21286199/858bb512-c41b-11e6-8799-1caa735e29ba.png)
![2016-12-17_05 31 00](https://cloud.githubusercontent.com/assets/24620601/21286200/858ce126-c41b-11e6-99c3-e515d492e571.png)

Edit: This started in an earlier version of your mods and persisted after updating both ExtremeReactors and ZeroCore.

**Comment by ZeroNoRyouki** [comment]
I can reproduce the first half of the problem, not the bit about cables. With an Ender IO cable attached, power is being produced. If I then attach a capacitor to the cable it's get charged. Could you re-test it in your world please?

**Comment by ZeroNoRyouki** [comment]
First bit fixed

**Comment by Everdyin1** [comment]
Retested as you asked. Not sure what is different today other than a windows update went thru while i was asleep but now EnderIO conduits and capacitors will draw power. Mekanism still does not draw power from the turbines but that is easy enough to work around.

Thank you for the fast response. I'm looking forward to seeing this mod evolve further.

**Comment by RogueLogic** [comment]
Will Mekanism not work with the RF, Tesla, or either taps?

**Comment by chanzie** [comment]
I am running into the same problem as well in my world, mek worked fine with just the normal reactor non actively cooled but once I switched over no power production was taking place

**Comment by RogueLogic** [comment]
Again, what tap are you using?

**Comment by ZeroNoRyouki** [comment]
It's probably related to https://github.com/aidancbrady/Mekanism/issues/4027 and https://github.com/aidancbrady/Mekanism/issues/3821

**Comment by ZeroNoRyouki** [comment]
Fix is out
