### ISSUE TITLE
Reactor RF generation

### ISSUE THREAD

**Issue by ThorasCZ** [ZeroNoRyouki/BigReactors#58]
Hallo

I build stadard reactor inner size 3x1x3 with 4 fuel rods and diamond block as a coolant. He was to produce something about 1,5kRF but when i started i produced 2.3MRF/t and at 10% produce 250kRF/t. I dont know where is a problem . See pictures. Take it easy. [https://drive.google.com/open?id=0BwytjX1Uv56JZTJhMVM3N2tBT1k](url) [https://drive.google.com/open?id=0BwytjX1Uv56JLXR6X2hiUTZFYVk](url)

**Comment by ZeroNoRyouki** [comment]
Stupid question: are you using the default config file?

**Comment by ZeroNoRyouki** [comment]
Locally is working fine (1.52 KRF/t / 0.033 mB/t)

which version or ER are you using? Is it a mod pack?

**Comment by ThorasCZ** [comment]
Sorry i forget it. It is version 0.4.5.21 and it is direwolf20 modpack version 1.1.4 and configs was not changed

**Comment by Rixxaw** [comment]
DireWolf modified the default config file as he always does.  I noticed he changed the Fuel Consumption factor from 1.0 to 8.0 in the current version.  I changed that back hoping it would help with my issue of not transferring fluid between fluid ports, but it only made the reactors use less yellorium and didn't seem to affect my issue.

**Comment by RogueLogic** [comment]
_note before reading : I don't know a better way to word this. i also know this is not related to the main issue._

@Rixxaw why did you think that the value labeled `fuelUsageMultiplier` _(note "multiplier")_ would have anything do do with inter-multiblock communications? as you seem to have no clue as to what that number does ill explain it. when the reactor consumes fuel the amount that it calculates it should take is multiplied by this number (1.0 by default obv). this, quite obviously, does not change how the mod decides where, when, and how much water to send to applicable ports that may not even be found for, far far far, more complicated reasons.

**Comment by Rixxaw** [comment]
@RogueLogic Of course I didn't think it was directly related.  I changed the value hoping that the Dev's had tested things with default values, and that Direwolf's modification might have introduced some bug in the code.  I posted to indicate that I found this made no change and that I too was having the issue.  It found the fix for my system by rebuilding the multi-block.
