### ISSUE TITLE
Right clicking with reactor part in hand places, removes, opens gui for item clicked on

### ISSUE THREAD

**Issue by choekstr** [ZeroNoRyouki/BigReactors#6]
I added zerocore-1.10.2-0.0.8.0 and ExtremeReactors-1.9.4-0.4.5.8 to a stock FTB Unstable modpack, generated a brand new world, and built a reactor to test it out.  As I was building it if I had say a reactor glass in my hand and building the top and right clicked on a rod controller then the reactor glass would place, sound of placing is heard, it is seen being placed, then removed, then the gui for the rod controller opens.  Same for things like input/output port, controller, etc.

Not a serious issue but thought you might want to clean this up if possible.

**Comment by ZeroNoRyouki** [comment]
Hi there,
I removed the glitch

The fix will be included in the next release of the mod
