### ISSUE TITLE
[Suggestion] Liquids from Substratum mod

### ISSUE THREAD

**Issue by Dragnier** [ZeroNoRyouki/BigReactors#60]
Substratum has recipes and liquids that could be useful. Liquid versions of redstone, glowstone, and enderpearl. Also has some notable alloys made with those liquids; Signalum, Lumium, and Enderium.

**Comment by ZeroNoRyouki** [comment]
If they are using the same fluid name that Thermal Expansion used (has they should be if the fluid is the same) they are already supported (most of them anyway)

**Comment by MakeLord95** [comment]
I tested it in singleplayer, and they aren't supported. Could you add them as equivalents to Thermal Expansion ones, since it's the closest we can get to TE liquids

**Comment by RogueLogic** [comment]
It is currently. I heard down a long grape vine that a port of the Thermal series is in the works. Should still be added though.

**Comment by HenryLoenwind** [comment]
Um, the fluid names for the TE fluids are aren't actually correct.

https://github.com/ZeroNoRyouki/BigReactors/blob/master/src/main/java/erogenousbeef/bigreactors/common/BigReactors.java#L214

vs.

https://github.com/TheCBProject/ThermalFoundation/blob/master/src/main/java/cofh/thermalfoundation/fluid/TFFluids.java#L37

**Comment by ZeroNoRyouki** [comment]
They are, don't worry about it. I've already tested the fluids

**Comment by ZeroNoRyouki** [comment]
New release that support Substratum is up. I've nerfed them a bit because they are more easily made than the TE ones
