### ISSUE TITLE
Yellorium Ore Not Generating in any negative dimensions.

### ISSUE THREAD

**Issue by tfox83** [ZeroNoRyouki/BigReactors#62]
I am working on FTB Beyond and have moved the mining world/deep dark/EXU Quarry world to -2, -3, -4 respectfully to clean things up.  All my and other mod's ore gen is respecting this change except for yellorium from Extreme Reactors.  I even tested moving the mining world to a postive DIM and still no yellorium.  I can force this with custom ore gen, but figured loads of other packs may have this issue too.  Thanks so much for looking into this!

**Comment by RogueLogic** [comment]
There is a dim whitelist in the config for Extreme Reactors. Add the dimensions to it and you should be all good.

**Comment by tfox83** [comment]
I'm an idiot, completely missed that, thanks so much, sorry for bothering you!

**Comment by ZeroNoRyouki** [comment]
I'm testing a new config option to change the behavior of the worldgen whitelist to a blacklist. It should help modpack creators
