### ISSUE TITLE
Fluids cannot be used inside reactor

### ISSUE THREAD

**Issue by HenryLoenwind** [ZeroNoRyouki/BigReactors#63]
https://github.com/ZeroNoRyouki/BigReactors/blob/master/src/main/java/erogenousbeef/bigreactors/common/multiblock/MultiblockReactor.java#L674 rejects all blocks that don't have an item...

**Comment by HenryLoenwind** [comment]
Let's start with: All Ender IO fluids.

**Comment by ZeroNoRyouki** [comment]
I've looked at it quickly and that null check can be more or less safely removed. Adding some of Ender IO fluids as moderators is on my TODO list: are you guys planning to do it from your side?

**Comment by HenryLoenwind** [comment]
Already done, that's how I came upon this.

https://github.com/SleepyTrousers/EnderIO/commit/408299c299110d47275bf051fcbd6df73ac972b1

Feel free to suggest better values, I don't really understand the calculations behind them and just took the existing registrations as an example and tweaked them a little bit.

I tested with this: https://gist.github.com/HenryLoenwind/00bc66aa7373c373065356fdad878bda

**Comment by ZeroNoRyouki** [comment]
I've just added a comment on the commit regarding the moderators values

**Comment by ZeroNoRyouki** [comment]
New release without the ItemBlock requirement is up

Z
