### ISSUE TITLE
Other Mod power transfer items not supported.

### ISSUE THREAD

**Issue by llloyd4** [ZeroNoRyouki/BigReactors#65]
Ok, Minecraft 1.10.2, Extreme Reactors 4.5.23 . If I connect any other cable / wire to Extreme Reactors RF Flux Tap the little light on the port stays red and no power is transferred out of the reactor. I've tried it with Mekanism Universal Cables and Draconic Evolution Energy I/O crystals, neither work, but it *does* work if I switch to Energy Conduits from Ender I/O. So far *only* if I use Ender I/O Energy Conduits.

**Comment by RogueLogic** [comment]
That is because EnderIO is FU capable. Even Mekanism's universal cables do not support this energy standard. My recommendation if you want to use the universal cables is to use the Tesla power tap until this is fixed.

@ZeroNoRyouki: _Please drop RF support in 1.11, it needs to die now._

**Comment by llloyd4** [comment]
Do I dare ask what "FU" is? Or are we talking about a bad word followed by 'you'? >.< I'll give the Tesla tap a whirl. Will the Tesla tap work with Draconic Evolution energy I/O stuff too? It's also not working. :(

**Comment by RogueLogic** [comment]
FU refers to both Forge Energy and my thoughts regarding it ("**** you"). No Draconic Evolution only supports RF sadly. Mechanism and EIO both have Tesla support.

**Comment by ZeroNoRyouki** [comment]
@llloyd4 : I'll check what's up with Draconic Evolution. Are you using a specific mod pack? 
Thank you for the report

@RogueLogic : I will drop it if TE drop it. It's still widely used out there

**Comment by llloyd4** [comment]
Direwolf20 1.10.2 slightly modified, I've added Cyclic, Foamfix, Mekanism, Simply Jetpacks 2, Slugs Converters, and Solar Flux Reborn. Just updated the mods too to A: see if a newer version would have fixed this and B: to get Extra Utilities 2 demon ingots to behave.

**Comment by ZeroNoRyouki** [comment]
Draconic Evolution Energy I/O crystals are now working. Retested Mekanism but there is still something funny with their cables. Connecting a cube directly to the Power Tap correctly fill the cube

DE fix will be included in the next release
