### ISSUE TITLE
The fluid ice is not valid for the reactor's interior

### ISSUE THREAD

**Issue by llloyd4** [ZeroNoRyouki/BigReactors#66]
Eh? It's no Cryothium but Cryothium isn't available in 1.10.2 so ... Same for packed ice. O.o *continues testing* Nope to Hardened Ice. Nope to IC2 Coolant (and that's meant for IC2 Reactors. O.o). Umm... Well, that's all I tested, liquified ender, from Ender IO, works.

**Comment by RogueLogic** [comment]
1st: Cryothium is available. However, I don't believe it is public yet.
2nd: ZeroNoRyouki/BigReactors#63
3rd: There are many things missing.

**Comment by llloyd4** [comment]
It is? Bleh. I just got done filling the reactor with Liquid Ender with no real change to the temperature over the graphite blocks, which is to say it's peaked out hot. And I am not sure I completely understand the other post? Is it saying that in the future Ender I/O and Forestry liquids and blocks will be added? As cold ice should, in theory, cool it right down, and IC2 Coolant is, AFAIK, for cooling reactors so... I am trying to get the temps down and the efficiency up, just the Big Reactor simulator page isn't updated yet for 1.10.2. >.<

**Comment by RogueLogic** [comment]
you are aware that it does not work that way right? both IRL and in ER. I cannot explain the algorithm but I'm sure Zero can.

**Comment by llloyd4** [comment]
What doesn't work what way, temp vs efficiency ? It says on the GUI:

Core Heat: Heat of the reactor's fuel. High heat raises fuel usage. 

So I need a colder core to reduce fuel usage and make it more efficient, yes? It's why I've always used Cryothium.

**Comment by ZeroNoRyouki** [comment]
@llloyd4: the basic idea here is... play with mod :) experiment with fuel rods layouts and moderators (blocks and fluids inside the reactor)

How good a moderator is depend on what that moderator represent and, more importantly, how rare or difficult to create it is. That's the reason why Substratum Liquid Ender is not as good as the old Ender from Thermal Expansion

Ender IO is adding it's own blocks/fluids as moderators. Other mods can do that too (that's way ER come with an API to do just that)

I'll take your suggestion and I'll check IC2 coolants. I may or may not add it naively

**Comment by ZeroNoRyouki** [comment]
Ender IO "Liquid Ender" is registered under the same name of Thermal Liquid Ender so it's using the same moderation data. For their other moderators, we discussed about the appropriate values

**Comment by llloyd4** [comment]
Ah, ok. As in the days of yore it was Crytothium then Liquid Ender were the top two coolants. Well, I'll have to build a second reactor for experimentation, can't have the main reactor down long and draining and refilling a 11x11x11 reactor is a royal pain. >.<

**Comment by RogueLogic** [comment]
there is creative mode...

**Comment by llloyd4** [comment]
True, still will use a small reactor to toss various stuff into. So what's better, a pure reactor or a turbine? I am thinking of getting into Draconic and to feed a 2tb rf storage globe will take a long time at 50k rf/t. O.o

**Comment by llloyd4** [comment]
I know this is *old* but how much of this got carried forward? - https://ftbwiki.org/Big_Reactors

**Comment by RogueLogic** [comment]
The turbine is far superior in yellorium consumption/(T/t) but it has a much higher setup cost/(T/t)

**Comment by llloyd4** [comment]
Setup cost is fine, I am still working my way though the tonne of stuff I got from a max size RFTools Builder in Quarry mode (512x256x512) being run in The Underdark. >.< Just, so far, until the other bug popped up (separate post, naturally) I was unimpressed with the RF/t output. A 11x11 5 high reactor putting out 1675 mb/t of steam, the 80 blade turbine was putting out at most 7k rf/t with a manyullyn double coil and that was the best up to that point. O.o My 11x11x11 reactor puts out 67k rf/t .

**Comment by RogueLogic** [comment]
A 2k mb/t turbine can produce up to 27KT/t with a coil of 37 enderium blocks and a little more with 32 ludicrite. depeding on design and coolant your reactor may be able to produce 50B/t with a lower fuel burn.

**Comment by llloyd4** [comment]
50 Billion? O.o That, I presume, is a max sized reactor?

**Comment by RogueLogic** [comment]
Buckets... that can power 25 turbines maxing at around 7 million T/t

**Comment by llloyd4** [comment]
Oh! O.o I wish I had an Extreme Reactor simulator to test designs quicker. I tried Vibrant blocks for coolant, water, liquid ender, etc and couldn't get above 20 mbb/t until I made the reactor bigger from 5, 5 high, cores to one with 25 5 high cores and am putting out 1675 mb/t, then back though the various coolants and that never wavered. Though a 10 long rotor, 8 blades (4 double) per rotor, 80 total blade segments, and it was stabilizing at 722 ish mb/t and maintaining 1800 rpm. So I am thinking it needs to be 20 long, 4 per segment, 80 blades for a 2k mb/t turbine?

**Comment by ZeroNoRyouki** [comment]
Guys, could you please continue your discussion somewhere else? (hint: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2731713-extreme-reactors-a-big-reactors-port-to-mc-1-9-4) 

The issue page is not a good place to talk about how the mod works. Also, you discussion can help other too

**Comment by ZeroNoRyouki** [comment]
I've checked the IC2 Coolant and as it is basically water + some lapis it's extremely cheap to make so it will not make that much of a moderator (just a bit better then plain water). It will probably not be included in the default moderators
