### ISSUE TITLE
Crash when Flux networks is placed next to non-output block on reactor

### ISSUE THREAD

**Issue by thetechnodragon** [ZeroNoRyouki/BigReactors#68]
http://pastebin.com/qepVcxcJ
the crash is re-create able with the latest extreme reactors and flux networks
minecraft version 1.10.2
extreme reactors version 1.10.2-0.4.5.23
flux networks version 1.10.2-1.0.9
how to re-create:

 1. build functional extreme reactor (does not need fuel)
 2. place either send or recieve node next to reactor on a non output block (if you put it on the output it connects just fine, no crashes, and interacts with the network fine)
 3. game crashes with no such method error

**Comment by RogueLogic** [comment]
Have you reported this to the Flux network dev(s)? this doesn't seem like an ER problem.

**Comment by ZeroNoRyouki** [comment]
It's indeed a problem in Flux Networks / SonarCore : https://github.com/SonarSonic/Flux-Networks/issues/32
