### ISSUE TITLE
Reactor Fluid Port next to turbine port doesn't transfer

### ISSUE THREAD

**Issue by Rixxaw** [ZeroNoRyouki/BigReactors#69]
I setup a Reactor and placed a turbine right next to it.  I used two fluid ports on each multi-block right next to each other.  I used the Extreme Reactors wrench to match the colors.  I then powered everything up and noticed I couldn't get above 200 mb per tick.  I moved the multi-block reactor over 1 space and placed pipes between the ports and I see fluid.  I was able to get somewhere between 200 and 300 mb per tick, But I am essentially limited in steam generation to how much water I can pipe into the reactor per tick.  Using DW20 pack I only have 2 fluid piping options, and two water generating options.  Extra Utilities Fluid Transfer node doesn't seem to work like it used too and you can only seem to get about 200 mb per tick out of it.  The Reservoir will only do about 1 bucket a second.  So at this time without re-using the water from the Turbine there isn't a good way to generate RF because you can't seem to get water into the reactor.

The way this worked before was primarily based on water from the turbine being piped directly to the reactor if they were placed side by side.  However the videos show using Mechanism pipes which are not available normally.  Please restore the ability of the fluid ports placed next to each other to pipe directly into each other in order to make your entire turbine multi-block useful without adding a mod like Mechanism.

**Comment by Rixxaw** [comment]
I am using 1.10.2-0.4.5.23

**Comment by ZeroNoRyouki** [comment]
#59 

Please check all other issues before posting a new one, thank you

**Comment by Rixxaw** [comment]
Sorry, I'm new to Github, and you have to read rather deep into that issue before you discover it  being the same issue I'm facing.  I will test with the fix indicated.

**Comment by ZeroNoRyouki** [comment]
No prob

**Comment by Rixxaw** [comment]
To confirm this did Fix the issue for me!  Thanks Zero you Rock!
