### ISSUE TITLE
[1.10.2] Crash using Universal Cable Mekanism with Tesla Power Tap

### ISSUE THREAD

**Issue by Morpheus1101** [ZeroNoRyouki/BigReactors#7]
My World crashes everytime on load now Crash log @ http://pastebin.com/bdAGKyKr

https://github.com/aidancbrady/Mekanism/issues/3714

**Comment by ZeroNoRyouki** [comment]
It looks like that Mekanism is still using the old Tesla modid ("tesla") instead of the new one ("Tesla") so is code is begin stripped out by FML and you get that crash because I'm calling a Mekanism provided methods that don't exist now

**Comment by ZeroNoRyouki** [comment]
He actually use the 2 modid at once, so it will depend on the version of Tesla you are using

**Comment by ZeroNoRyouki** [comment]
Try to update to a new version of Tesla (the one you are using use "tesla" as it's modit, mekanism expect "Tesla")

**Comment by Morpheus1101** [comment]
Loaded with latest vers of tesla and 1st Attempt Game loads and when starts to render forces game in stopped state and force close of game.  Will try again and grab fml-latest log etc.

**Comment by Morpheus1101** [comment]
Tesla 1.2.1.48 crash on join still crash log @ http://pastebin.com/NvcRHt6g
[fml-client-latest.txt](https://github.com/ZeroNoRyouki/BigReactors/files/441838/fml-client-latest.txt)

**Comment by ZeroNoRyouki** [comment]
Sorry about the confusion on the modid, you are obviously right (non-lowercase modid are going to be stopped by some next version of FML). The crash is still the same so you were already using a version of Tesla with the lowercase modid. But Mekanism still check if "Tesla" is around

**Comment by Morpheus1101** [comment]
ok so its a problem Mekanism side then not BR
