### ISSUE TITLE
Alpha release for 1.10.2 has no textures for mod added blocks after updating.

### ISSUE THREAD

**Issue by ate0ate** [ZeroNoRyouki/BigReactors#70]
The ore blocks as well as all of the others just have the black and purple squares texture after updating and loading an existing world. They seem to exist, but just don't display. This is using forge 12.18.3.2221 and the alpha zerocore 0.1.0.2

**Comment by TheRandomLabs** [comment]
I am also having this issue with the exact same versions.

**Comment by ate0ate** [comment]
Unfortunately, reverting back to the prior versions of extreme reactors and zerocore results in a corrupted save file. Fortunately, since there was plenty of warning that this was an experimental alpha, I used a backup save, but it is definitely worth mentioning. Also upon loading my world after reverting to the older mod versions I did get the usual notice of blocks no longer existing from forge that you normally see after removing a mod, which seemed odd. So, in summary, updating to the alpha release results in untextured blocks and attempting to revert results in missing blocks and a corrupted save.

**Comment by ZeroNoRyouki** [comment]
There is a problem with some blockstate files in the 1.10.2 jar, that's why you see no texture. Not all of them were packaged in the jar with the correct name

Blocks and items names changed between .24 and .25 (camelCase to all lowercase) so yes, going back will result in missing blocks

**Comment by ZeroNoRyouki** [comment]
Fixed in 1.10.2-0.4.5.26
