### ISSUE TITLE
TechReborn Cables Compatibility Problem

### ISSUE THREAD

**Issue by kenijey** [ZeroNoRyouki/BigReactors#71]
The RF power tap isn't compatible with techreborn cables. can you fix it? or techreborn should fix it? or you can make a FE power tap for tech reborn?
using 1.11.2 forge 2222

**Comment by ZeroNoRyouki** [comment]
The Redstone Flux Power Taps already support the Forge Energy system

**Comment by kenijey** [comment]
We can not connect Insulated Copper Cable in TechReborn to the RF Power Tap. I mean this.

**Comment by ZeroNoRyouki** [comment]
Ops, sorry about that.

I checked it and they don't connect indeed. But I tested it also with Gendustry and Environmental Tech machines and the cables don't connect or provide power (from a TR generator) either. It looks like a problem on their side of the fence

**Comment by kenijey** [comment]
yes :((( and they did never listen my suggestions about cable compatibility. 
hey, can you make a universal cable for 1.11.2? it would be really really really really AWESOME. you would be our hero...
i was using galacticraft 3's aluminum wires in 1.7.10. they were all compatible with the all mods :)
and... please do that man... make a universal conduit or cable or wire or something pleeease...

**Comment by ZeroNoRyouki** [comment]
Sorry but I'm pretty busy as I am right now :) Maybe in the future who knows :)

**Comment by kenijey** [comment]
ohh i got it now, TechReborn uses Forge Energy. Their cables compatible with this. You should add a FE power tap...  You should support Forge man :D

**Comment by ZeroNoRyouki** [comment]
Like I said, the Redstone Flux Power Taps already support the Forge Energy system

**Comment by kenijey** [comment]
oh, i tried something and got success. i tried placing MFSU near the RF Power Tap. And MFSU filled. But cable does not compatible like MFSU...weird..

**Comment by RogueLogic** [comment]
That is because the code to connect the MFSU is different from the code used to connect the cables.

**Comment by ZeroNoRyouki** [comment]
I asked one of TR devs: their cables don't connect to other machines by design. Case closed.

**Comment by kenijey** [comment]
omg, why is that... it is so bad... really. at least they should connect to forestry machines... it is very unsensible and annoying.

**Comment by RogueLogic** [comment]
bring that up with them, im sure they have a good reason.

**Comment by kenijey** [comment]
...

**Comment by RogueLogic** [comment]
if you would like to ask directly you can, they have a discord server that can be found on the TR [github page](https://github.com/TechReborn/TechReborn).
