### ISSUE TITLE
Yellorite, Yellorium, etc. Missing Textures

### ISSUE THREAD

**Issue by Darkosto** [ZeroNoRyouki/BigReactors#72]
I've update to the latest version of Extreme Reactors and discovered the textures are missing for Yellorite Ore, ingots, blocks, and dust. They seem to function correctly, so it's just a visual bug at the moment.

MC: 1.10.2
Extreme Reactors: 0.4.5.25
Forge: 2221

https://sx.artdude.uk/hotlink-ok/darkosto/7dF4-a5a19-1485115234.png

**Comment by Darkosto** [comment]
Actually, looking further, the issue is most items in Extreme Reactors: https://sx.artdude.uk/hotlink-ok/darkosto/gaDN-04cd2-1485116562.png

**Comment by RogueLogic** [comment]
AHEM: ZeroNoRyouki/BigReactors#70, need I say more about this?
