### ISSUE TITLE
[1.10.2] Yellorite is not spawning in the AromaCore Mining World Dim 6

### ISSUE THREAD

**Issue by Redlotus99** [ZeroNoRyouki/BigReactors#73]
I have added Dimension 6 to the whitelist in the cfg for Extreme Reactors and it has not generated after a world reset.

In the cfg I have 0 and 6 listed and have even just listed 6 and still have had no luck.

Forge: 2221
ExtremeReactors-1.10.2-0.4.5.24.jar

Config: http://pastebin.com/wsNvLxD6

Any help would be appreciated.
Possibly related: https://github.com/ZeroNoRyouki/BigReactors/issues/15

**Comment by RogueLogic** [comment]
i assume you traveled to a new area of the world and tested it?

**Comment by Redlotus99** [comment]
Yes I have also completely deleted Dim 6 and restarted the server.

**Comment by ZeroNoRyouki** [comment]
I've tested it with Dimensional-World-1.9.4-1.2.0.6 / Aroma1997Core-1.9.4-1.1.1.1 / Forge 12.18.3.2221 and it's working fine.

Are you sure that 6 is the correct Id in your pack / aroma config?

**Comment by Redlotus99** [comment]
Can you send me the config you used to produce this? Maybe I missed something.

**Comment by ZeroNoRyouki** [comment]
Sure

Here it is : http://pastebin.com/wViLkNsi

**Comment by Redlotus99** [comment]
Thank you very much. I'll test it out. I'm assuming it is something on my end. Thank you again for the quick help.
