### ISSUE TITLE
invalid block not touching reactor (pics included)

### ISSUE THREAD

**Issue by MaxMega12** [ZeroNoRyouki/BigReactors#75]
Hi,
I am making a 15x15x15 passive reactor.
However, I get a message saying:
"-394, 56, -1296 - Block is not valid for use in the machine's interior".
I check the coordinate, but it is not connected to the reactor. (diamond block in pic)
What could be happening?
![2017-01-29_18 37 46](https://cloud.githubusercontent.com/assets/11894558/22409085/61f4a47a-e652-11e6-9858-068f59502741.png)
![2017-01-29_18 37 58](https://cloud.githubusercontent.com/assets/11894558/22409086/61f53cfa-e652-11e6-8876-e0737163b3e4.png)
![2017-01-29_18 38 09](https://cloud.githubusercontent.com/assets/11894558/22409084/61f47dce-e652-11e6-9e9b-dc642656bd2c.png)

**Comment by RogueLogic** [comment]
What version of ZeroCore and ExtremeReactors are you using? This appears to be on 1.7.10 so if you could provide a screen shot with the F3 debug shown that would also be useful.
A world zip would be very useful to reproduce this error.

**Comment by MaxMega12** [comment]
Thanks for responding,
I am not using ExtremeReactors, rather the original BigReactors version 0.4.3A for 1.7.10.
Could installing ExtremeReactors fix the problem?
![2017-01-29_19 32 41](https://cloud.githubusercontent.com/assets/11894558/22409601/0f93c1f4-e65a-11e6-9ec0-832ea3b8b018.png)

**Comment by RogueLogic** [comment]
Big Reactors 1.7.10 is no longer supported, period.
Updating to Extreme Reactors should fix the problems, and in the case that it doesn't there is active development.
_note: extreme reactors only runs on 1.9.4 and newer so you will need to update all of your mods._

**Comment by MaxMega12** [comment]
alright, thanks!
