### ISSUE TITLE
Minimum size on horizontal axle turbines

### ISSUE THREAD

**Issue by forrester-marc** [ZeroNoRyouki/BigReactors#77]
A vertical axis turbine can be four layers high at minimum, but will not assemble if built horizontally.  A fifth layer is required if rotated.

Error code: zerocore:zerocore:api.multiblock.validation.machine_too_small

**Comment by RogueLogic** [comment]
That is because the minimum dimension ins x,y,z format is 5,4,5; by default.
You can change these values int the config.

**Comment by forrester-marc** [comment]
The minimums in the default config make sense, the issue is that they don't rotate with the alignment of the build.  This makes the effective minimum for a horizontal axle turbine 5,5,5 where it should be 4,5,5 or 5,5,4.

**Comment by RogueLogic** [comment]
The ZeroCore API does not care about the turbine axle orientation, that is a custom specification. It is possible to do what you are saying but its more complicated than merely changing the numbers, and mostly useless. Most turbines exceed the limits regardless and if you need a small one build it vertical.

**Comment by forrester-marc** [comment]
Ah, so ZeroCore doesn't really support machines with different orientations.  Do you think anything could break if I set the server minimums to 4,4,4?

**Comment by RogueLogic** [comment]
No.

**Comment by forrester-marc** [comment]
Robust coding FTW.  That's solved, then, thanks!
