### ISSUE TITLE
[1.10.2] Crash on connect after creating a reactor.

### ISSUE THREAD

**Issue by UnPure** [ZeroNoRyouki/BigReactors#78]
Hey there.
I just created my 7x7x7 Reactor.
It has 25 Fuel Rods, 5 Control Rods, 2 Access Ports, 1 RF Power Port and 1 Controller.
Its filled with 100x Block of Lead (I think its from IC2 but i'm not 100% sure) and is build without any glass, only casing.
After placing the last block, my client crashed. Now every time i'm connecting my client is crashing again.

Minecraft: 1.10.2
Forge: 12.18.3.2221
Extreme Reactors: 0.4.5.24
ZeroCore: 0.1.0.3

Crashlog: http://pastebin.com/kgwSp8nV
fml-client-latest: https://gist.github.com/UnPure/2000d7c37f33fbb07fa6e902b05f4271

If you need any other informations, just le me know.
Sorry for my bad english, i hope its not to hard to understand.

**Comment by ZeroNoRyouki** [comment]
Update ER to version 1.10.2-0.4.5.26

**Comment by UnPure** [comment]
Thats seems to fix the problem, thank you.
I already looked for a newer version but for some reason i thought 0.4.5.26 would be for 1.11.2, i'm sorry.
