### ISSUE TITLE
Getting crash when i use any cables on tesla power tap

### ISSUE THREAD

**Issue by Realever** [ZeroNoRyouki/BigReactors#8]
Hi,
i have crashes when i connect a cable or from FluxNetworks the flux-plug to the tesla power tap if i link it to the flux controller then the game crash and i cannot load the world unless i delete the mod that connect to the tesla power tap.Here is the crash report:  http://pastebin.com/9UFXbczw

**Comment by ZeroNoRyouki** [comment]
Hi, and thank you for the report

I've fixed the crash and uploaded a new version (1.9.4-0.4.5.10).
