### ISSUE TITLE
[REQUEST] Fuel rods color depending on the inserted fuel

### ISSUE THREAD

**Issue by Bobynoby** [ZeroNoRyouki/BigReactors#81]
(This is not a bug but a request)

If possible, Could you add in the ability of the fuel rod changing color depending on the fuels color. Like Yellorium makes the rods yellow but Uranium (From immersive engineering for example) makes it a dark green. Its just that I have a small mod that i'm making and there's a uranium type of fuel that's purple (Don't ask why) and I thought it would be cool for the reactors rods to be purple.

Again this is just a request, But It would be a cool bit of detail to the mod :).

**Comment by ZeroNoRyouki** [comment]
Hi
You can already do that. When you register a new fuel one of the data you need to supply is the fluid color

Z
