### ISSUE TITLE
Water tank size limits maximum output in active cooling mode

### ISSUE THREAD

**Issue by Killerhurtz** [ZeroNoRyouki/BigReactors#82]
Keep in mind, this problem is a thing since Big Reactors and I currently have not played in a while (computer broke) so this issue might be moot.

But last I know about, the size of a reactor's water tank effectively limits it's maximum power output to something like 2k or 20k mb of steam, because it vaporizes the whole tank of water in a single tick (and because there is no more water for that tick, any more power results in reactor heat instead of steam). 

So unless I'm missing something (does adding multiple fluid inputs add to tank capacity?), either having a block (possibly using that nearly pointless space in most designs), or a parameter (like empty space) to increase the water capacity, or having it somehow account for the tick water input to produce more steam, would be great.

Unless of course it's as designed for balance purposes.

**Comment by RogueLogic** [comment]
ZeroNoRyouki/BigReactors#40

**Comment by Killerhurtz** [comment]
Yes sorry, didn't think it would be in something like that. Closing.

**Comment by Killerhurtz** [comment]
Yes sorry, didn't think it would be in something like that. Closing.

**Comment by ZeroNoRyouki** [comment]
Yes, the tank size is a balancing factor and an incentive to build more reactors
