### ISSUE TITLE
[1.10.2] "Max"-Size Reactor not valid.

### ISSUE THREAD

**Issue by UnPure** [ZeroNoRyouki/BigReactors#83]
Hey there.
I'm currently building a max size reactor in my creative test world.
To make the fuel rod pattern a little bit better, the size of the reactor is 31x31 and 48 height.
After placing the last block the multiblock is forming, but the reactor is not working.
On right click it tells me that a block from the reactor walls isnt valid.
I tried replacing the walls with glass but i still get invalid messages.
I tried rebuilding the complete reactor but its always the same.
"Reactor glass may only be used on the exterior faces, not as part of a reactor's frame or interior."
I checked it again and again but the reactor frame is build with reactor casing and the interior is build out of fuel rods and block of manyullyn.
I checked the configs but the are default so the size should be no problem.
Is there anything else i'm missing?

Forge: 12.18.3.2221
ER: 0.4.5.26
ZeroCore: 0.1.0.3

**Comment by RogueLogic** [comment]
Is that internal or external dimensions?

**Comment by ZeroNoRyouki** [comment]
Your reactor is probably too big. 

Keep in mind that you can't use glass on the frame, only on the internal space of each face

**Comment by UnPure** [comment]
The size (31x31x48) is external, the frame is as i said completly out of casings.
The config has these values:

```
    # The maximum valid size of a reactor in the Y dimension, in blocks. Lower this if your server's players are building ginormous reactors. Bigger Y sizes have far less performance impact than X/Z sizes
    I:maxReactorHeight=48

    # The maximum valid size of a reactor in the X/Z plane, in blocks. Lower this if your server's players are building ginormous reactors
    I:maxReactorSize=32

```

**Comment by ZeroNoRyouki** [comment]
I was thinking you were talking about the internal size

Could you post some screenshots of the reactor layout and of the error?

**Comment by UnPure** [comment]
The problem is "fixed" now. I was building the reactor 32x32 at the beginning before i decided to go with 31x31. I had to break all the blocks from the outside and it seems like somehow 2 blocks stayed as a ghost.
I dont know why the multiblock was formed and i dont know why it wasnt complaining about the two blocks at one of the reactor sides.

**Comment by RogueLogic** [comment]
Because the algorithm is old and this situation was not reported to the original dev, it checks that before checking for a complete frame.

**Comment by scollenburg** [comment]
I can confirm this behavior. Having casing blocks next to a complete frame will cause issues -- **the easy workaround being to remove them.**

And I'd be slow to pass too harsh of judgement on the algorithm -- identifying extraneous blocks is difficult & computationally expensive.

**Comment by RogueLogic** [comment]
It's not hard nor too computationally expensive to iterate over the frame first... Not of you know what you are doing making the algorithm

**Comment by RogueLogic** [comment]
Ok, Zero you should be able to just paste [this](http://pastebin.com/ppYQibAR) code [here](https://github.com/ZeroNoRyouki/ZeroCore/blob/master/src/main/java/it/zerono/mods/zerocore/api/multiblock/rectangular/RectangularMultiblockControllerBase.java#L73) or [here](https://github.com/ZeroNoRyouki/BigReactors/blob/master/src/main/java/erogenousbeef/bigreactors/common/multiblock/MultiblockReactor.java#L388) so that it will show a frame issue instead.

**Comment by ZeroNoRyouki** [comment]
@UnPure no ghost block should be left around. How did you brake them?

**Comment by UnPure** [comment]
I was using the 5x5 draconic staff from DE in creative mode to break all the unneeded blocks.

**Comment by ZeroNoRyouki** [comment]
Thank you. I'll check it and see what's happening

**Comment by UnPure** [comment]
Dont forget that i was breaking about 3000 blocks and only 2 blocks of them stayed as a ghost, could take a few tries. :D

**Comment by ZeroNoRyouki** [comment]
Yeah I know, Looking forward to a fun evening ... :)

**Comment by ZeroNoRyouki** [comment]
So, I took an indirect approach to this. Given the rarity of the situation, I've chosen to not put code in to detect possible ghosts for now. I have a system in place to detect misalignment between the server and the client but for now it's disabled.

What I did was to add two new functionalities to the mod wrench: while holding it in the off-hand you can use it on a multiblock to get back it's starting and ending coordinates (as seen by the "server"). If you sneak while doing so you would force an update of all the blocks enclosed in that area

You can find the updated wrench in the next release
