### ISSUE TITLE
Reactor multiblock wont form

### ISSUE THREAD

**Issue by falizure** [ZeroNoRyouki/BigReactors#84]
I tried assembling a extreme reactor today, in 2 different configurations, a basic 3x3x3 and a 5x5x5, with a controller, 2 access ports, and 1 and 3 fuel rods respectively, 1 control rod, and tested with both rf and tesla power ports, when completing the structure it doesnt form, clicking anywhere on the reactor except the access ports which functions normally (although doesnt insert fuel into the rods) reports that all blocks must be of the same tier, when in our version the legacy version is the only version of blocks available, we are running version 1.10.2-0.4.5.26

**Comment by yepidoodles** [comment]
SpongeForge: 2221-5.1.0-BETA-2147
Forge: 2221

**Comment by ZeroNoRyouki** [comment]
Did you craft all the blocks or did you got any from other sources (JEI, /give, etc)?

Also, could you check all the reactor blocks by looking at them with the debug screen (F3) open? In the bottom-right corner you should see the block state information of the block you are looking at. Does any block show anything different than tier:legacy ? If so, could you get me a screenshot please?

**Comment by falizure** [comment]
all crafted, ill check the f3 now
ok the fuel rod says tier basic, it also has no texture when held.

**Comment by ZeroNoRyouki** [comment]
how did you craft that fuel rod?

**Comment by falizure** [comment]
in a applied energistics crafting terminal using the jei + feature to fill the crafting grid, if your asking what materials im not sure, we have immersive engineering uranium which is unified with the yellorium so it might have used ether or during the crafting.

**Comment by falizure** [comment]
jei says legacy but when in a crafting grid it says basic.

**Comment by ZeroNoRyouki** [comment]
OK, problem found. It's adding a recipe it should not at the moment. I'll fix it in the next release

Just craft the rod with iron instead of steel for the moment

**Comment by falizure** [comment]
i am unable to do so as i am playing on a server which is using the steel recipe not iron, so i can not change it, but i will talk with the admin yepidoodles tomorrow.

**Comment by ZeroNoRyouki** [comment]
Fixed in next release
