### ISSUE TITLE
Crafting reactors with anything Inside Crashes

### ISSUE THREAD

**Issue by Dewfire** [ZeroNoRyouki/BigReactors#85]
I've attempted to built a couple reactors both on our server and in Single Creative and as long as I leave the inside empty with air, the reactor forms with no issues.  But if I place water, diamond blocks etc inside it crashes when I place any further blocks.

Water on Server World, client logs:
[http://pastebin.com/ytC8XGgc](http://pastebin.com/ytC8XGgc)

Diamond Blocks Solo World:
[http://pastebin.com/ytC8XGgc](http://pastebin.com/txHMAbKe)

In creative I used JEI blocks spawned in, on server I crafted them in an AE terminal so not sure if this is related to the previous issue or not.

This is from the Ardentcraft Mod pack off Curse btw.

**Comment by ZeroNoRyouki** [comment]
See #78
