### ISSUE TITLE
Missing tooltips in reactor controller UI

### ISSUE THREAD

**Issue by scollenburg** [ZeroNoRyouki/BigReactors#86]
Extreme Reactors 1.10.2 0.4.5.24
Forge 12.18.3.2215

The 4 setting buttons on the lower left of the UI are not rendering a tooltip on hover:

- Eject automatically
- Do not eject
- Activate reactor
- Deactivate reactor

I know what they do from playing 1.7x, and the buttons work, just no tooltips.

Please add the tooltips when you can. Thanks!

**Comment by ZeroNoRyouki** [comment]
I'll add the eject/don't eject tooltips

**Comment by ZeroNoRyouki** [comment]
All tooltips added (next release)
