### ISSUE TITLE
Question - Reactors additions

### ISSUE THREAD

**Issue by YOYOK9** [ZeroNoRyouki/BigReactors#88]
This is more of a question then an issue. I know when BR was being worked on there was different talks about the reactor possibly exploding if it hit a certain point or something. Would you possibly think about doing something like this down the road? 

Maybe something like if the reactor is too hot when being water cooled it will "break" and explode. Or if it is just creating energy if it runs out of fuel and is too hot or something,. Just a thought.

**Comment by ZeroNoRyouki** [comment]
Yes, structural damage and explosion are among the things on our TODO list. Radiations too

For the future, please use the forum (http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2731713-extreme-reactors-a-big-reactors-port-to-mc-1-9-4-1?page=6) for questions / suggestions so other players can pitch in too
