### ISSUE TITLE
Reactor/Turbine not connected properly

### ISSUE THREAD

**Issue by AleShade** [ZeroNoRyouki/BigReactors#89]
In SkyFactory 3.0.7, with ExtremeReactors 0.4.5.26 I have two weird issue. The first one is that I cannot make a setup reactor/turbine with coolant port directly attached to each other, cause the turbine doesn't output water without something that import/export it. The second one is that if I exit from my world , I have to break one block of the reactor and add it again to have it output steam directly to the turbine next to it or it won't work.
I hope I was clear, I'm not that good in english.

**Comment by FailMelon** [comment]
Having same issues here it seems to happen when the chunk unloads the coolant ports touching doesn't seem to push water to the reactor from the turbine. It fixes after breaking the turbine controller so possibly an issue with the turbine.

**Comment by patrix87** [comment]
This is likely the same issue than this https://github.com/ZeroNoRyouki/BigReactors/issues/98

**Comment by RogueLogic** [comment]
#59

**Comment by ZeroNoRyouki** [comment]
Yes, It's the same problem as in #98
