### ISSUE TITLE
No Retrogen support

### ISSUE THREAD

**Issue by MakerTim** [ZeroNoRyouki/BigReactors#9]
For oregen, why u dont use forge IWorldGenerator,
All the retrogen mods cant work without it :/

**Comment by ZeroNoRyouki** [comment]
We use it, and we have our own retrogen facility. Enable it in the config

**Comment by MakerTim** [comment]
sorry, CPW his SimpleRetrogen mod din't listed it in his list command..
also; the retrogen option does nothing

**Comment by ZeroNoRyouki** [comment]
Don't worry.

I've re-tested the retrogen code when you opened this issue. I started from a "vanilla" world (just MC + Forge) and then added BR and it generated the ores

Are you using the last version of Extreme Reactors and ZeroCore?
