### ISSUE TITLE
what is yellorite ore command

### ISSUE THREAD

**Issue by andsim** [ZeroNoRyouki/BigReactors#91]
hi am trying to use /give command in yellorite ore but there no command on extremerectors: when i press tab auto complete
can you please fix this thank

**Comment by RogueLogic** [comment]
I'm sorry is the /give command syntax to hard for you? That also has nothing to do with extreme reactors.

**Comment by ZeroNoRyouki** [comment]
The modid is still bigreactors

Z

**Comment by andsim** [comment]
is bigreactors is mod name?

**Comment by ZeroNoRyouki** [comment]
No, it's the mod identifier (or modid for short)
