### ISSUE TITLE
what is command for yellorite_ore

### ISSUE THREAD

**Issue by andsim** [ZeroNoRyouki/BigReactors#92]
try locate bigreactors:yellorite_ore there none in command in /give playername bigreactors:yellorite_ore

**Comment by scollenburg** [comment]
Try `bigreactors:brOre`, and / or check your JEI / NEI.

**Comment by andsim** [comment]
ok why i cant i use in rftools dimiension?

**Comment by scollenburg** [comment]
There are lots of things that affect cross mod interactions, most of which are *not* bugs. This is probably a great question to ask over in reddit.

https://www.reddit.com/r/feedthebeast/

And if turns out to be a bug with Extreme Reactors is found then follow up here.

**Comment by ZeroNoRyouki** [comment]
Please us the forum thread to ask questions. The issue page is only for reporting bugs
