### ISSUE TITLE
[1.10.2] Thermal Expansion Support

### ISSUE THREAD

**Issue by SnowShock35** [ZeroNoRyouki/BigReactors#93]
Hi,

Would it be at all possible to get Thermal Expansion support for ER? Since Thermal Expansion for 1.10.2 is now out, Extreme Reactors lacks such support for the relevant machines. E.g. Pulverizer, Redstone Furnace, etc. 

Thanks.

**Comment by ZeroNoRyouki** [comment]
Yes, I'am working on it

**Comment by SnowShock35** [comment]
@ZeroNoRyouki Yaay \o/ ❤️

**Comment by XFactHD** [comment]
May I add the request for support of the TE metal blocks as turbine coils? That would be really great.

**Comment by RogueLogic** [comment]
Iirc those already work so long as TE didn't change its registry names.

**Comment by XFactHD** [comment]
No, they do not work, I tried Signalum Blocks and the Turbine refused them.

**Comment by RogueLogic** [comment]
[_ahem_](https://github.com/ZeroNoRyouki/BigReactors/blob/master/src/main/java/erogenousbeef/bigreactors/common/BigReactors.java#L131:L173)

**Comment by XFactHD** [comment]
Thank you, I didn't know that, but the Signalum Block is missing nonetheless.

**Comment by ZeroNoRyouki** [comment]
Machines support is back in 0.4.5.28. I did not add Signalum and similar materials because they are basically copper/tin with a touch of something else
