### ISSUE TITLE
[1.10.2] Yellorite Ore doesn't spawning in Deep Dark

### ISSUE THREAD

**Issue by PanSzelescik** [ZeroNoRyouki/BigReactors#95]
Hello!
My English is not perfect. Sorry :/
I have problem. Yellorite doesn't spawning in Deep Dark in author modification package. I have about 90 mods. I give the versions of those referred.
Extra Utilities 2 - 1.3.3
Extreme Reactors - 0.4.5.27
ZeroCore - 0.1.0.4
Forge - 2254
What should I change in config file? Yellorite has no place.

**Comment by RogueLogic** [comment]
Dimension white-list, add the dimension ID of the Deep Dark.
