### ISSUE TITLE
[Suggestion] Coolant In/Out Valve

### ISSUE THREAD

**Issue by MokahTGS** [ZeroNoRyouki/BigReactors#96]
I'd love to have a block added that pumps coolant into and out off a reactor structure once its formed.  This would make incremental changes to the reactor so much easier.

**Comment by RogueLogic** [comment]
1st: Coolant is not necessarily fluid (unless you are referring to active reactor coolant, in which case there already is)
2nd: AFAIK the placement of the blocks/fluid is supported to be a manual process, if given different blocks this would either be extremely dumb or give you the perfect reactor. They all do have different properties after all.

**Comment by MokahTGS** [comment]
Alright, then I might not understand the coolant system.  Is there a wiki with what blocks/liquids can be used as coolant and what the properties are of each?

**Comment by RogueLogic** [comment]
the IIRC FTBWiki still has correct information and anything not posted there is in the code [here](https://github.com/ZeroNoRyouki/BigReactors/blob/master/src/main/java/erogenousbeef/bigreactors/common/BigReactors.java#L106:L229). you are free to mix and match these blocks/fluids inside the reactor.
There are also complications with re-scanning the reactor and etc other things that would make this problematic.

**Comment by ZeroNoRyouki** [comment]
What you call "coolants" are, in reality, reactants that moderate the "neutrons" radiating from the fuel rods (and yes, cool them down in the process by moving heat away from them). The material used and it's placement inside the reactor is a key design factor and basically the name of the game while building any kind of reactor

So thank you for you suggestion but no, I will not add a mechanism to automatically place reactants inside the reactor. Experimenting with many materials and design is a key component of the game play of the mod ;)
