### ISSUE TITLE
JEI not showing yellorium

### ISSUE THREAD

**Issue by NerdCraft** [ZeroNoRyouki/BigReactors#97]
![2017-04-10_19 36 53](https://cloud.githubusercontent.com/assets/13489837/24885504/2f515e72-1e25-11e7-9bba-c9378d2f4278.png)

**Comment by ZeroNoRyouki** [comment]
Works fine here...

![2017-04-11_01 19 14](https://cloud.githubusercontent.com/assets/7107662/24886454/f9a30e9e-1e54-11e7-8688-587097ca06b9.png)

Which versions are you using?

**Comment by NerdCraft** [comment]
Minecraft: 1.10.2
Forge: 12.18.3.2281
Extreme Reactors: 0.4.5.27
Zero Core: 0.1.0.4

maybe this is a bug with UniDict (https://minecraft.curseforge.com/projects/unidict), yellorium isn't showing in ore dictionary converter too.
![2017-04-10_20 35 05](https://cloud.githubusercontent.com/assets/13489837/24886760/36e0c814-1e2d-11e7-83f9-737ea30da534.png)

**Comment by ZeroNoRyouki** [comment]
I've tested it again with JEI 1.10.2-3.14.7.417 + UniDict 1.10.2-2.8 + Industrial Craft 2 2.6.188-ex110 (to have another ingotUranium around) and it's working fine too:

![2017-04-11_10 18 40](https://cloud.githubusercontent.com/assets/7107662/24899494/be05ca38-1ea0-11e7-9a8d-3e6031c93cf7.png)

It's probably some configuration in the mod pack you are using

**Comment by NerdCraft** [comment]
![sem titulo](https://cloud.githubusercontent.com/assets/13489837/24919537/69e373b4-1eba-11e7-9d94-681d1fcac7fa.png)

i'm feeling stupid, sorry about this
